### ISSUE TITLE
Use different scopes for different users

### ISSUE THREAD

**Issue by grantmcconnaughey** [python-social-auth/social-core#10]
*Note: I am using `python-social-auth` with Django 1.9*

Is there any way to request different scopes depending on which user is logging in? I have followed [this documentation](http://python-social-auth.readthedocs.io/en/latest/use_cases.html#multiple-scopes-per-provider) to enable private repos if `private` is in the query string. This is what it looks like:

```python
from social.backends.github import GithubOAuth2 as SocialGithubOAuth2

class GithubOAuth2(SocialGithubOAuth2):
    """
    A GitHub OAuth backend that adds private repo scope if private is in the query string.
    """
    def get_scope(self):
        scope = super(GithubOAuth2, self).get_scope()
        if self.data.get('private'):
            scope = scope + ['repo']
        return scope
```

And here are my default scopes:

```python
SOCIAL_AUTH_GITHUB_SCOPE = [
    'user',
    'read:org',
    'public_repo',
    'admin:repo_hook',
]
```

I'd really like to be able to change the scope depending on the *user* that is logging in, not just based on the query string.

My app requests the minimum scope at signup (public repos only). Then the user can enable private repos later on, in which case I redirect them to login with `private=1` in the query string. That adds the `repo` scope when authenticating with GitHub. Then some time will go by, they'll get logged out, and next time they login they'll go right back to the public-only scope.

I need to be able to capture the user that is logging in and change their scope with GitHub when authenticating. Is there any way to accomplish this with python-social-auth?

**Comment by omab** [comment]
There's no way to know in advance which user will be authenticating, some options that come to my mind right now are:

1. Store some value in the session and determine the needed scopes in the `get_scope()` override based on that value, but that won't be 100% reliable IMO
2. Let the user go through the usual authentication, then in the pipeline check if the user had the extra scope granted, and redirect them to the beginning with `private=1` again
3. Override `extra_data` method and also store the extra scope when authorized, then avoid updating the access token since they don't expire on github.

**Comment by grantmcconnaughey** [comment]
Hey @omab, thanks a lot for the ideas. I'll go ahead and close this issue.

**Comment by grantmcconnaughey** [comment]
Hey @omab, just wanted to let you know that option 3 worked really well for me. In the spirit of giving back, here's my GitHub OAuth2 class that implements this. It should be useful if anyone asks a question like this in the future:

```python
from social.backends.github import GithubOAuth2 as SocialGithubOAuth2


class GithubOAuth2(SocialGithubOAuth2):
    """
    A GitHub OAuth backend that adds private repo scope if private is in the query string.
    """

    PRIVATE_REPO_SCOPE = 'repo'

    EXTRA_DATA = [
        ('scope', 'scope'),
    ] + SocialGithubOAuth2.EXTRA_DATA

    def get_scope(self):
        scope = super(GithubOAuth2, self).get_scope()
        if self.data.get('private'):
            scope = scope + [self.PRIVATE_REPO_SCOPE]
        return scope

    def extra_data(self, user, uid, response, details=None, *args, **kwargs):
        """
        Checks if the user has enabled private repos and, if so, ensures that their
        private repo access token isn't overridden.
        """
        data = super(GithubOAuth2, self).extra_data(user, uid, response,
                                                    details=details,
                                                    *args, **kwargs)

        social_auth = user.social_auth.filter(provider=self.name).first()
        private_enabled = self._has_enabled_private_repos(social_auth)

        if private_enabled:
            data['access_token'] = social_auth.extra_data.get('access_token')

        return data

    def _has_enabled_private_repos(self, social_auth):
        if social_auth and social_auth.extra_data:
            current_scopes = social_auth.extra_data.get('scope').split(',')
            return self.PRIVATE_REPO_SCOPE in current_scopes
        else:
            return False
```
