### ISSUE TITLE
Email couldn't be validated

### ISSUE THREAD

**Issue by zavod** [python-social-auth/social-core#103]
I'm trying to validate Email by ModelBackend and everything all right if the user clicks one time on the validation link, but if he clicks twice he got the error: 
`Email couldn't be validated`

How can I handle it and show beautiful HTML for the user like "You already activated your account"?

Second error if the user uses another browser for activating Email, he got the error: 
`Missing needed parameter email`

How can I do it?

**Comment by omab** [comment]
(Assuming Django) You can trap and improve the rendering of errors by extending the exceptions middleware, docs https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#exceptions-middleware
