### ISSUE TITLE
BitbucketOAuth2 backend has no `refresh_token()` method implementation

### ISSUE THREAD

**Issue by nkprince007** [python-social-auth/social-core#104]
Related Issue in Django-app: https://github.com/python-social-auth/social-app-django/issues/67

Related Code: https://github.com/python-social-auth/social-core/blob/master/social_core/backends/bitbucket.py#L84-L86

This is crucial in developing our [GitMate-2](https://code.gitmate.io) with Bitbucket support, their tokens expire often and we need some modular method to refresh them deterministically. Please report soon.

**Comment by nkprince007** [comment]
We worked about a fix for this. But, FWIW, just lift off the overridden `refresh_token` method in `social_core/backends/bitbucket.py` for `BitbucketOAuth2`. It works right away. :)

**Comment by omab** [comment]
PRs are always welcome!
