### ISSUE TITLE
SAML IDP config in database

### ISSUE THREAD

**Issue by dblado** [python-social-auth/social-core#107]
Moved this issue from social-app-django since it's more relevant to core

In a multi tenant environment, I want to let my admins specify the IDP in an admin interface. Is there a recommendation for how to CRUD the SOCIAL_AUTH_SAML_ENABLED_IDPS in the database?

**Comment by omab** [comment]
For that to happen, you need to override the default strategy in order to extend it to retrieve settings from the database instead of the framework settings.
