### ISSUE TITLE
NotUniqueError at /complete/email multiple clicks to mail_validation link

### ISSUE THREAD

**Issue by dblado** [python-social-auth/social-core#108]
When a user clicks the mail validation link a second time, I see duplicate key errors. I'm looking at adding a pipeline function reclick_email_verification_check that would 
- redirect '/' if the user was authenticated already
- or redirect to a page telling the user to log in 

I found that the pipeline continues each time so I would have to add that after each pipeline function after mail_validation.

```
    'social_core.pipeline.mail.mail_validation',
    # 'social_core.pipeline.social_auth.associate_by_email',
    'users.social_pipeline.reclick_email_verification_check',
    'social_core.pipeline.user.create_user',
    'users.social_pipeline.reclick_email_verification_check',
    'social_core.pipeline.social_auth.associate_user',
    'users.social_pipeline.reclick_email_verification_check',
    'social_core.pipeline.social_auth.load_extra_data',
    'users.social_pipeline.reclick_email_verification_check',
    'social_core.pipeline.user.user_details',
```

That's when I decided that I must be missing something obvious :)

Any ideas?

**Comment by dblado** [comment]
FYI, here is the stacktrace if you click the validation link a 2nd time:

```
Internal Server Error: /complete/email/

NotUniqueError at /complete/email/ Tried to save duplicate unique keys (E11000 duplicate key error collection: vendop.user_social_auth index: uid_1_provider_1 dup key: { : “email_address@gmail.com”, : “email” })
```

**Comment by omab** [comment]
How much time does it pass between clicks? Does it look like a race condition scenario?
