### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by codingjoe** [python-social-auth/social-core#11]
v0.1.0
> Remove Facebook2OAuth2 and Facebook2AppOAuth2 backends (port from #1046 by browniebroke)

This small line almost took down our production system. I would appreciate if you would really stick with Semantic Versioning. If you remove or change behavior you should to make a major release.

Happy New Year
-Joe

**Comment by omab** [comment]
I'll try.

**Comment by codingjoe** [comment]
@omab thanks, I just read my comment again. I could have said that much nicer. Sorry
I really appreciate all the hard work!
