### ISSUE TITLE
Backend for Microsoft Graph

### ISSUE THREAD

**Issue by leonholub** [python-social-auth/social-core#113]
The Microsoft Graph API is currently not supported by any backend. With a new backend similar to AzureAD i got it to work using social-app-django.
See pr #114 
I will try to provide tests as well if you plan to integrate it.

**Comment by NBajanca** [comment]
> To call Microsoft Graph, your app must acquire an access token from Azure Active Directory (Azure AD), Microsoft's cloud identity service.
Source: [Microsoft Graph Docs](https://docs.microsoft.com/pt-pt/azure/active-directory/develop/active-directory-authentication-libraries)

I'm using Graph with the current [AzureADOAuth2](http://python-social-auth.readthedocs.io/en/latest/backends/azuread.html). The trick was setting ``RESOURCE = 'https://graph.microsoft.com/'``, as described in [DOCS](http://python-social-auth.readthedocs.io/en/latest/backends/azuread.html).

If you need help integrating it with AzureAD let me know and I will try to help.

**Comment by Khouli00** [comment]
For information I have tried to use this backend,with the new application registration portal as described by Microsoft.

> New app registrations should be created and managed in the new Application Registration Portal to be compatible with Outlook.com. 

However I  get the following error : 

```
AADSTS50020: We are unable to issue tokens from this api version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.
```

**Comment by NBajanca** [comment]
I didn't notice your pr was for ad v2.0! Sorry for my comment
Why not azure ad v2.0 instead of Microsoft Graph for the backend name?

**Comment by jpatel3** [comment]
is this change already available? I am also running into the same error while making the call.

**Comment by omab** [comment]
Related PR already merged.
