### ISSUE TITLE
Missing requirement for `jwkest`

### ISSUE THREAD

**Issue by IlianIliev** [python-social-auth/social-core#121]
I have `python-social-auth[django]==0.3.6` in my `requirements.txt` which install `social-core`.

This module https://github.com/python-social-auth/social-core/blob/master/social_core/backends/open_id_connect.py#L6 relies on `jwkest` to be installed, but the package is not in the requirements and does not get installed.

**Comment by IlianIliev** [comment]
Sorry, this was probably my bad due to using the new version of the package but installed the old way.
When I actually removed everything and installed `social-auth-app-django` everything is fine.

**Comment by IlianIliev** [comment]
However as the package is still a requirement of the `social-core` maybe it should be in the core requirements.

**Comment by omab** [comment]
There's an [extra](https://github.com/python-social-auth/social-core/blob/master/setup.py#L85) defined for that, but you need to install `social-core[openidconnect]`, which I guess must be explicitly defined in your `requirements.txt` file as such.

**Comment by fnordian** [comment]
How do I install social-core[openidconnect]?

`pip install 'social-core[openidconnect]'`

gives me:

> Collecting social_core[openidconnect]
>  Could not find a version that satisfies the requirement social_core[openidconnect] (from versions: )
> No matching distribution found for social_core[openidconnect]

**Comment by sinistag** [comment]
@fnordian try `pip install 'social-auth-core[openidconnect]'`
