### ISSUE TITLE
No module named 'urlparse' with python 3.5 and Oauth 1 (Flickr)

### ISSUE THREAD

**Issue by mushahid54** [python-social-auth/social-core#122]
`Oauth (1)` Supported By `Flickr` giving error:
> No module named 'urlparse'

Exception Location: | /Users/abc/python-virtual-environments/prod_env/lib/python3.5/site-packages/oauth/oauth.py in <module>, line 29
-- | --

Whats I am using:
```
Python : 3.5
djangorestframework==3.6.2
social-auth-app-django==1.2.0
social-auth-core==1.3.0
```

It would be great if anyone can assist with this.

**Comment by omab** [comment]
Closing, reopen if still valid and with more details please, full-traceback would be very useful since the line denoted above is not from this lib, but a dependency.
