### ISSUE TITLE
social_django and Gmail API

### ISSUE THREAD

**Issue by lanec** [python-social-auth/social-core#125]
I'm building a tool to look into email data kind of like Unroll.me if you are familiar with it.

To start out my team and I began using the django-social-auth library and found that it could authenticate us into an account and stored the account meta data in the Django projects database.  

Next we found the Google Gmail API had some sample code here: https://developers.google.com/gmail/api/quickstart/python 

This code worked to allow access to our users Gmail data but didn't store the email or meta data in the database to authenticate the user within the Django application. 

These two approaches apparently use both the Google Plus API and the Gmail API.  Each of these has a different URL.  Is there a way to authenticate against one API and store the credential to authenticate against another?

Is there a way to marry the two so users only need to sign in once but Django can store the email/meta data in the database and we can go through emails stored in Gmail?

Thanks for any help you can offer!

**Comment by lanec** [comment]
@omab Is there any sample code you can think of for facilitating this?

**Comment by omab** [comment]
@lanec there are two parts on this problem:

1. Authenticate users with the right permission to access Gmail API
2. Access Gmail API and grab the data you need

`python-social-auth` solves just the first point, you need to specify the permissions needed to access Gmail API, there's a full list [here](https://developers.google.com/gmail/api/auth/scopes#gmail_scopes). Just define them in the `SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE` setting and let the users authenticate with Google OAuth2. If using Google Plus, then set the values in the setting `SOCIAL_AUTH_GOOGLE_PLUS_SCOPE`.

To solve the second, you need to write the code to pull the emails and store them in your database the best way it fits your need, once you have the user authenticated, you will have an `access_token` stored in the db, using that token will grant you access to Gmail API to call any of the API endpoints (authorized by the scope selected).

Here's an snippet about how to call the Gmail API, this example just retrieves the email ids, but you can tune it to fit your case.

```python
import httplib2

from datetime import datetime

from apiclient.discovery import build
from oauth2client.client import OAuth2Credentials

from django.conf import settings

from social_django.models import UserSocialAuth

# Assuming user to be an instance of an user that authenticated through google:
usa = user.social_auth.get(provider="google-oauth2")  # or provider="google-plus"
revoke_uri = None
user_agent = 'PythonSocialAuth'

credentials = OAuth2Credentials(
    usa.extra_data['access_token'],
    settings.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
    settings.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET,
    usa.extra_data['refresh_token'],
    datetime.fromtimestamp(usa.extra_data['auth_time']),
    revoke_uri,
    user_agent,
    scopes=settings.SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE
)

http = httplib2.Http()
http = credentials.authorize(http)
service = build('gmail', 'v1', http=http)

emails = service.users().messages().list(
    userId=usa.user.email,
    q='FROM:lane@joinjune.com'
).execute()

# emails contains a dict like:
# {'messages': [{'id': '15e34e63191fa12f', 'threadId': '15e34e63191fa12f'}],
#  'resultSizeEstimate': 1}

# Remember to set the SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE
# to any of the options listed at: https://developers.google.com/gmail/api/auth/scopes
```

**Comment by imomaliev** [comment]
For future reference `oauth2client` is depricated in favor of `google-auth`

```python
from datetime import datetime

from requests import exceptions as requests_errors

from google.auth.exceptions import RefreshError
from google.oauth2.credentials import Credentials as GoogleCredentials

from social_django.utils import load_strategy

class Credentials(GoogleCredentials):
    """Google auth credentials using python social auth under the hood"""

    def _parse_expiry(self, data):
        """
        Parses the expiry field from a data into a datetime.

        Args:
             data (Mapping): extra_data from UserSocialAuth model
        Returns:
             datetime: The expiration
        """
        return datetime.fromtimestamp(data['auth_time'] + data['expires'])

    def __init__(self, usa):
        """
        Args:
            usa (UserSocialAuth): UserSocialAuth google-oauth2 object
        """
        backend = usa.get_backend_instance(load_strategy())
        data = usa.extra_data
        token = data['access_token']
        refresh_token = data['refresh_token']
        token_uri = backend.refresh_token_url()
        client_id, client_secret = backend.get_key_and_secret()
        scopes = backend.get_scope()
        # id_token is not provided with GoogleOAuth2 backend
        super().__init__(
            token, refresh_token=refresh_token, id_token=None,
            token_uri=token_uri, client_id=client_id, client_secret=client_secret,
            scopes=scopes
        )
        self.usa = usa
        # Needed for self.expired() check
        self.expiry = self._parse_expiry(data)

    def refresh(self, request):
        """Refreshes the access token.

        Args:
            request (google.auth.transport.Request): The object used to make
                HTTP requests.

        Raises:
            google.auth.exceptions.RefreshError: If the credentials could
                not be refreshed.
        """
        usa = self.usa
        try:
            usa.refresh_token(load_strategy())
        except requests_errors.HTTPError as e:
            raise RefreshError(e)
        data = usa.extra_data
        self.token = data['access_token']
        self._refresh_token = data['refresh_token']
        self.expiry = self._parse_expiry(data)

# Usage
usa = user.social_auth.get(provider="google-oauth2")
service = discovery.build('gmail', 'v1', credentials=Credentials(usa))
emails = service.users().messages().list(
    userId=usa.user.email,
    q='FROM:lane@joinjune.com'
).execute()
```

**Comment by thatsankur** [comment]
Thanks @imomaliev This helped a lot!
