### ISSUE TITLE
OpenID Connect backends leave Extra Data still JWT encoded by default.

### ISSUE THREAD

**Issue by techdragon** [python-social-auth/social-core#127]
If this is by design, fair enough. The level of documentation on using OpenID Connect does it no favours in terms of how sure I am this is a bug. But regardless...

The extra data section of the user object does not decode the JWT payload when using OpenID Connect, which is what you would expect based on its purpose "store the extra stuff about users from the Auth provider".  I would have expected something to happen more like what the author of this gist https://gist.github.com/kakky/6809432 has done, where the JWT is verified decoded and the payload added to the user_data dictionary.

Is this something that belongs in a custom OpenID Connect backend? or is this something that the base class should be doing?

**Comment by zulrang** [comment]
This is by design as the backend doesn't have to assume what's in your extra data.

Override the get_user_details() function in your custom backend, decode the JWT, and return a dict of what you want from the extra data.
