### ISSUE TITLE
Facebook backend not retrieving email

### ISSUE THREAD

**Issue by donaldharvey** [python-social-auth/social-core#131]
We recently experienced an issue where the response from the Facebook graph API at `/me` just after authenticating didn't contain an email field. It's hard to say if this issue is present for everyone, or whether it's just an issue with our site - in Ruby's `omniauth`, users experiencing the issue seemed to be experiencing it intermittently: https://github.com/mkdynamic/omniauth-facebook/issues/61

Adding `SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id,name,email,first_name,last_name'}` to our settings made it work.

To avoid this problem in the future, perhaps it would be good to have the `user_data` method make the request with a reasonable default set of fields, including email?

**Comment by dmwyatt** [comment]
I can't tell from your description if you realize this, but [the docs specifically mention](http://python-social-auth-docs.readthedocs.io/en/latest/backends/facebook.html#oauth2) that to get the email address you should do what you did.

**Comment by donaldharvey** [comment]
Ah sorry, my bad! I did read the docs here but must have missed the mention of `EXTRA_PARAMS`. In past versions of PSA, it had worked just by setting `SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']`.

Maybe it would still be useful to set `fields` by default?

**Comment by omab** [comment]
As the doc says, you need the scope and the fields defined in the setting, this is on purpose to avoid adding a value that attempts to make everybody happy but can easily fail given that what you get is directly related to the scope defined.

**Comment by zxwild** [comment]
The docs are removed and I tried to find what's wrong for about 3 hours in my facebook app and all places which I could imagine.
It's a nice joke from your side, guys.

**Comment by dmwyatt** [comment]
@zxwild What do you mean the docs are removed?  The link in my comment just up thread a bit still works...

**Comment by zxwild** [comment]
@dmwyatt
I just realize, my adblock (ublock) blocks the facebook docs section as a social ads,
`<div class="section" id="facebook">`
First time I see such thing, just empty page, only the menu is shown.
