### ISSUE TITLE
Getting 500 instead of 401

### ISSUE THREAD

**Issue by hovi** [python-social-auth/social-core#135]
Hi,

after last update, my server responds to unauthorised api requests with 500 instead of 401, I can see it is probably result of this commit:
c955d66ee9d54828bfd7df3c44f3a1afc5056bbc

My clients are used to refresh their access tokens on 401 and now don't work anymore. Is this change correct? Doesn't seem so. If it is, how should I reconfigure to make sure I am still getting 401 for unauthorised requests?

**Comment by mhozza** [comment]
Actually, that code does not change much - it specifies the correct exception to be thrown instead of generic exception thrown in the else branch. The effect of this is that the django backend will handle it correctly and show a message instead of throwing 500.
