### ISSUE TITLE
partial pipeline resume wrong

### ISSUE THREAD

**Issue by HiveMe** [python-social-auth/social-core#136]
i wrote a partial pipeline,which used for force user to login/register a website account.The partial pipeline will redirect user to a login/regiseter page to associate website account.and here is the problem is:
when i use a social account ,for example social_account_A,to login the website,it's show me the login/register page,that's right.then i change the url to example.com/login/google, and use another social_account_B,pipeline will continue excute,so social_account_B can not login/register,all the parital data belongs to social_account_A,how can i resove this problem,or it's a bug to be repaired

**Comment by scdekov** [comment]
@HiveMe Did you resolve this?

**Comment by HiveMe** [comment]
@scdekov yes, issue #145 it's the right anwser for me.if you have same problem,you can just update your social-core version,this problem has been fiexed.when you need a paritial pipeline,just use it as follow:
`@partial_step(save_to_session=False)`.It should be work normally.
