### ISSUE TITLE
Deleting expired partial pipelines

### ISSUE THREAD

**Issue by remcinerney** [python-social-auth/social-core#139]
My social_auth_partial table is expanding a lot as I am using a passwordless email login system.

Should these entries automatically be deleted once they are expired?
I can't find any docs related to dealing with these, nor anything related to them expiring (either through the pipeline being completed, or some time dependency).

**Comment by omab** [comment]
If you are using the django integration app, there's a built-in command to cleanup outdated entries (email verification code and expired partial data).
