### ISSUE TITLE
New auto EXTRA_DATA field: psa_expires_on

### ISSUE THREAD

**Issue by NBajanca** [python-social-auth/social-core#14]
According to [IETF](https://tools.ietf.org/html/rfc6749#section-4.2.2), one of the fields in an OAuth2 response should be ``expires_in``.

So far all the providers I've worked with return this field but I have no way to work with it because a time stamp of the access token is not saved. 
I've added a pipeline where I add ``expires_on`` to the EXTRA_DATA that is basically:

     expires_on = int(time.time()) + int(expires_in)

This way I can get my ``access_token`` allways valid (django code!):

    social = request.user.social_auth.get(provider='my-backend')
    if social.extra_data['expires_on'] <= int(time.time()):
        strategy = load_strategy()
        social.refresh_token(strategy)
    return social.extra_data['access_token']

I have availability to do this improvement myself (fork, push) but I would like to have some feedback.

My idea would be to alter the class ``BaseOAuth2`` (OAuth1 doens't have expires_in, at least in RFC) with:

    expires_in = response.get('expires_in', '') or \
                               kwargs.get('expires_in')
    if expires_in not '':
    	data['psa_expires_on'] = int(time.time()) + int(expires_in)
    else:
    	data['psa_expires_on'] = None

I added ``psa`` to the beginning because at least AzureAD Oauth2 protocol replies with ``expires_on``, precisely with this implementation (epoch time)

In the long term, something interesting would be to include a method, like the one I have at the beginning of this issue, to obtain the access token. It would be an alternative to ``social.extra_data['access_token']`` and would assure the token obtained is valid.

**Comment by omab** [comment]
With https://github.com/python-social-auth/social-core/commit/920ca3f85048a94fdcdde33a229833c600e0f68e I've added `auth_time` by default for any backend, the value is also used by `expiration_timedelta()` (previously named `expiration_datetime()`, an alias was added to keep the backward compatibility), and by `access_token_expired()`.
