### ISSUE TITLE
How to authenticate against single tenant Azure AD apps

### ISSUE THREAD

**Issue by fthiery** [python-social-auth/social-core#140]
Hi; just succeeded, with Microsoft's help, to setup multi-tenant authentication. My two mistakes were that - i was missing the reply url in my app registration configuration
- i didn't define my app to be multi-tenant in the azure portal app registration

According to MS support, the "common" namespace in the hardcoded urls below refer to common / multi-tenant-only setups.

In: ./social-core/social_core/backends/azuread.py
```
    AUTHORIZATION_URL = \
        'https://login.microsoftonline.com/common/oauth2/authorize'
    ACCESS_TOKEN_URL = 'https://login.microsoftonline.com/common/oauth2/token'
```
1) am i correct here in assuming that in order for single-tenant to work, i need to patch/extend social-core's Azure AD backend to allow overriding AUTHORIZATION_URL and ACCESS_TOKEN_URL (or add a TENANT conf variable), so that all requests go to https://login.microsoftonline.com/mytenant/ instead ? Or is that already possible ?
2) shouldn't the http://python-social-auth-docs.readthedocs.io/en/latest/backends/azuread.html documentation mention that this is only for multi-tenant apps ? I can contribute here but i'd like confirmation beforehand

**Comment by htukiain** [comment]
Had a same issue and considering doing PR for AUTHORIZATION_URL and ACCESS_TOKEN_URL  overrides.
