### ISSUE TITLE
social_core setup.py may detect wrong python version when using pipenv

### ISSUE THREAD

**Issue by jmichalicek** [python-social-auth/social-core#142]
With the new pipenv, which is [recommended by python.org now](https://packaging.python.org/new-tutorials/installing-and-using-packages/#installing-pipenv), there are issues with using os.sys_version in setup.py to determine which dependencies to install.

It appears that since pipenv technically runs in your main python environment rather than inside the virtualenv it manages, setup.py detects that python version.  So for example I use python 3.6 as my main python, but have a few legacy projects which are on 2.7 for now.  If I use pipenv then social_core's setup.py sees python 3.6 in os.sys_version and pops python3-openid into the requirements rather than python-openid.

Would it be possible to use the `extras_require` feature of setuptools 18.0 and up to handle the conditional dependency?

Please also see https://github.com/kennethreitz/pipenv/issues/924

**Comment by jmichalicek** [comment]
Any thoughts on this?  I made the PR which switches to using python environment markers rather than relying on detecting the currently executing python version.  This allows everything to play together nicely within the current officially supported and recommended installation methods.

**Comment by wooyek** [comment]
When I used [pip-compile](https://github.com/jazzband/pip-tools) to freeze requirements, it outputs both:

python-openid==2.2.5      # via social-auth-core
python3-openid==3.1.0

Im not sure how it ended here. I was trying to reproduce it with a simpler case, but no with luck here. But anyway conditional dependency should solve the problem.

There is a tox-dev/tox#236 issue referencing this problem: https://github.com/tox-dev/tox/issues/236#issuecomment-247790512

**Comment by piotr-szpetkowski** [comment]
@jmichalicek Until this is resolved in here I've temporarily made a fork with your PR. I've also pushed my own PR and will review the other one when time permits

```
"social-auth-core" = {git = "https://github.com/sunscrapers/social-core.git"}
```
