### ISSUE TITLE
How to set PROXIES for requests?

### ISSUE THREAD

**Issue by POD666** [python-social-auth/social-core#146]
I was looking for a way to set proxy in order to make requests.
At the moment I've patched base backend:
```
proxies = getattr(settings, 'SOCIAL_SERVICES_PROXIES', {})
old_request = BaseAuth.request

@wraps(old_request)
def new_request(self, url, method='GET', *args, **kwargs):
    '''
    COPY-PASTE from social_core.backends.base import BaseAuth
    with proxy support
    '''
    kwargs.setdefault('headers', {})
    if self.setting('VERIFY_SSL') is not None:
        kwargs.setdefault('verify', self.setting('VERIFY_SSL'))
    kwargs.setdefault('timeout', self.setting('REQUESTS_TIMEOUT') or self.setting('URLOPEN_TIMEOUT'))
    if self.SEND_USER_AGENT and 'User-Agent' not in kwargs['headers']:
        kwargs['headers']['User-Agent'] = self.setting('USER_AGENT') or user_agent()

    kwargs.setdefault('proxies', proxies)  # main line

    try:
        if self.SSL_PROTOCOL:
            session = SSLHttpAdapter.ssl_adapter_session(self.SSL_PROTOCOL)
            response = session.request(method, url, *args, **kwargs)
        else:
            response = request(method, url, *args, **kwargs)
    except ConnectionError as err:
        LOG.info(str(kwargs))
        LOG.error(str(err))
        raise AuthFailed(self, str(err))
    response.raise_for_status()
    return response

BaseAuth.request = new_request
```
Is there a better way to do that?

**Comment by omab** [comment]
There's no explicit definition of proxies support in this lib, but I think you can accomplish the same by defining the environment values for `HTTP_PROXY` and/or `HTTPS_PROXY` [as documented in `requests` lib](http://docs.python-requests.org/en/master/user/advanced/#proxies).

**Comment by mreyk** [comment]
@omab Your solution does not work when working inside a virtualenv. For me, it only works with the workaround of @POD666 .

I do have the configuration of `HTTP_PROXY` and `HTTPS_PROXY` in `/etc/environment` and the `env_keep` in `/etc/sudoers`.

**Comment by POD666** [comment]
@omab I had a need to use different proxies to access different resources.
So env variables are not a solution.

**Comment by msadig** [comment]
@POD666 I have the same issue. where should this patch "live" in the code?

**Comment by msadig** [comment]
@POD666 I have the same issue, where should this patch "live" in the code?

**Comment by POD666** [comment]
@msadig Usually I create 'adapters' app for such purposes. Then I define [AppConfig](https://docs.djangoproject.com/en/2.0/ref/applications/#application-configuration) for each 3rd party lib patching and import exect patch in [`ready` method](https://docs.djangoproject.com/en/2.0/ref/applications/#django.apps.AppConfig.ready). So I can include those app in a right place in INSTALLED_APPS.
```
adapters/
    __init__.py
    apps.py
    patch_social_auth.py  # contains that code inside `def patch():`
    patch_something_other.py  # something other


# adapters/apps.py
from django.apps.config import AppConfig
from .patch_social_auth import patch as patch_social_auth
from .patch_something_other import patch as patch_something_other

class AddProxySupport(AppConfig):
    verbose_name = "Add proxy support "
    def ready(self):
        patch_social_auth()
...

# myproject/settings.py
INSTALLED_APPS = [
    # ...
    'adapters.apps.AddProxySupport',
    # ...
]
```

**Comment by rootVIII** [comment]
I just wrote a wrapper class here: https://github.com/rootVIII/proxy_requests 
It may be of some help...

**Comment by bd808** [comment]
A `SOCIAL_AUTH_PROXIES` config var seems to have been quietly added for this use case in 25ed3b6242e89f644b3d4a4d235496905b4bc9c1 as part of the 3.4.0 release.
