### ISSUE TITLE
Upgrading from django-social-auth

### ISSUE THREAD

**Issue by MounirMesselmeni** [python-social-auth/social-core#148]
Hi, the documentation of python social auth is not accessible anymore which makes the upgrade from django-social-auth quiet difficult, I tried to follow current upgrade instructions but it will generate migration issues because I did not upgraded to python-social-auth.

Is there any place where I can find documentation of python-social-auth or a direct migration from django-social-auth to social-core?
Thank you

**Comment by omab** [comment]
There's https://python-social-auth.readthedocs.io/en/latest/configuration/porting_from_dsa.html and https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md, but there's no documentation about directly going from `django-social-auth` to `social-core`.
