### ISSUE TITLE
Wrong url inferred for BambooHR OpenID Connect

### ISSUE THREAD

**Issue by teeberg** [python-social-auth/social-core#150]
I made a custom backend for BambooHR OpenID Connect that looks like this:
```python
from social_core.backends.open_id_connect import OpenIdConnectAuth
class BambooHROpenIdConnectAuth(OpenIdConnectAuth):
    name = 'bamboohr-oidc'
    @property
    def OIDC_ENDPOINT(self):
        return 'https://7geese.bamboohr.com'
```

The BambooHR OIDC config (e.g. https://7geese.bamboohr.com/.well-known/openid-configuration) specifies the `authorization_endpoint` as https://7geese.bamboohr.com/authorize.php?request=authorize. However, the code to generate the final authorization url here: https://github.com/python-social-auth/social-core/blob/2854a7e1d518f83662b7ad480ffe3ff069c02691/social_core/backends/oauth.py#L343
does not expect the authorization endpoint to already contain a query string and blindly adds another `?` before appending all other url parameters, resulting in an url that starts with something like https://7geese.bamboohr.com/authorize.php?request=authorize?nonce=..., i.e. two query strings?!

I was able to fix my specific issue by applying this patch:

```diff
diff --git a/social_core/backends/oauth.py b/social_core/backends/oauth.py
index 9f39842..a795636 100644
--- a/social_core/backends/oauth.py
+++ b/social_core/backends/oauth.py
@@ -335,12 +335,7 @@ class BaseOAuth2(OAuthAuth):
         params = self.auth_params(state)
         params.update(self.get_scope_argument())
         params.update(self.auth_extra_arguments())
-        params = urlencode(params)
-        if not self.REDIRECT_STATE:
-            # redirect_uri matching is strictly enforced, so match the
-            # providers value exactly.
-            params = unquote(params)
-        return '{0}?{1}'.format(self.authorization_url(), params)
+        return url_add_parameters(self.authorization_url(), params)
 
     def auth_complete_params(self, state=None):
         client_id, client_secret = self.get_key_and_secret()
```

but I assume throwing out the whole logic around the `REDIRECT_STATE` here can't be the right way to go. But I can't make sense of that logic: Why is the `params` string unquoted? Couldn't that lead to invalid urls if any of the params contain e.g. any of `?`, `#`, `&`?

A simpler fix could be to check if `?` is already included in `self.authorization_url()` and then use an `&` instead.

Happy to open a PR with a fix, but I feel I should understand the code around it first :-)

**Comment by omab** [comment]
You can define the extra arguments on a few ways:

1. Define `SOCIAL_AUTH_BAMBOOHR_OIDC_AUTH_EXTRA_ARGUMENTS = { 'request': 'authorize'}`
2. Override `auth_extra_arguments` to add the `request` parameter to the `dict`
3. Override `auth_params` to do the same as option 2

**Comment by petterreinholdtsen** [comment]
Isn't the point that https://github.com/python-social-auth/social-core/blob/master/social_core/backends/open_id_connect.py generate the wrong URL using the content of .well-known/openid-configuration?  It seem to me @omab is suggesting to leave open_id_connect.py as it is and fix the problem in each subclass.  Is it not better to fix it where the URLs are generated?
