### ISSUE TITLE
REVOKE_TOKENS_ON_DISCONNECT not documented

### ISSUE THREAD

**Issue by dmwyatt** [python-social-auth/social-core#151]
The setting `REVOKE_TOKENS_ON_DISCONNECT` is not documented anywhere.

This is an issue because [by default](https://github.com/python-social-auth/social-core/blob/0b04306855a3219be9578f5bf57ea51720e2546f/social_core/pipeline/disconnect.py#L20) it is `False`, but the default disconnect pipeline leads you to believe that the tokens are being revoked.

```
    # Revoke any access_token when possible.
    'social_core.pipeline.disconnect.revoke_tokens',
```

Is there a reason for this to default to False or for it being undocumented?  I'm a little unfamiliar with token revocation so that's why I didn't just submit a PR to fix the documentation.

AFAIK, the solution is to add documentation somewhere in the `Configuration` section of the docs.  Also, should the default disconnect pipeline include a stage that by default does nothing?

**Comment by omab** [comment]
I've [added docs](https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#account-disconnection) about the setting an the reasoning behind the default `False`. As for why it's in the pipeline even when nothing is done, that's to reduce the number of lines needed to enable this functionality, one setting vs a full disconnect pipeline.
