### ISSUE TITLE
JIRA backend for oauth

### ISSUE THREAD

**Issue by nkprince007** [python-social-auth/social-core#154]
Please add support for JIRA backend with oauth. Similar to bitbucket cloud, it'd be a lot helpful if we had support for JIRA Cloud and JIRA server alike.

**Comment by nkprince007** [comment]
Following [this guide](https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-oauth-authentication/?_ga=2.233769241.66806604.1510574415-588647914.1510574415), I'm trying to implement a backend for JIRA.

However, I'm facing a problem with the request token, I need to send in a RSA-SHA1 signing key for each request. I need help on how to configure it. Please help me out here.

**Comment by freyley** [comment]
Should this ticket be closed with the completion of an Atlassian OAuth2 class, or is it waiting for documentation to complete?
