### ISSUE TITLE
Drop python 3.3

### ISSUE THREAD

**Issue by sils** [python-social-auth/social-core#156]
How do you feel about dropping support for python 3.3?

- Python 3.3 never had a significant user base and wasn't part of any distribution's LTS release.
- It's support is dropped by many libraries, e.g. oauthlib hindering https://github.com/python-social-auth/social-core/issues/154

**Comment by hugovk** [comment]
+1 to dropping it.

Here's the pip installs for social-auth-core from PyPI for the last month (via `pypinfo --percent --pip social-auth-core pyversion`).

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   37.4% |         14,248 |
| 3.6            |   30.4% |         11,579 |
| 3.5            |   19.5% |          7,416 |
| 3.4            |   12.5% |          4,746 |
| 3.7            |    0.3% |            101 |
| 3.3            |    0.0% |              8 |
| None           |    0.0% |              7 |
| 2.6            |    0.0% |              4 |
| 3.2            |    0.0% |              1 |

That's a lower fraction than for all of PyPI (`pypinfo --percent --pip "" pyversion`):

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   78.0% |    454,240,817 |
| 3.6            |    8.6% |     50,301,669 |
| 3.5            |    8.3% |     48,225,874 |
| 3.4            |    3.8% |     22,052,677 |
| 2.6            |    1.1% |      6,341,968 |
| 3.3            |    0.1% |        610,051 |
| 3.7            |    0.1% |        460,986 |
| 3.2            |    0.0% |         44,590 |
| None           |    0.0% |         23,421 |
| 3.1            |    0.0% |             39 |
| 2.8            |    0.0% |             32 |

(PS social-core has over 60% Python 3! 👍 )

**Comment by tisdall** [comment]
In some projects I've seen support for earlier versions of 3 due to pypy3 (which was compatible with 3.3).  The latest pypy3 is now compatible with 3.5 . 

Incidentally, though, pypy3 doesn't seem to be included in travis.yml and should probably be included.

**Comment by omab** [comment]
I think this should do the trick for now https://github.com/python-social-auth/social-core/commit/a483c7e45b90e545c347b885b4553297e4d0b613.

Thanks
