### ISSUE TITLE
Backend for Azure Active Directory B2C

### ISSUE THREAD

**Issue by OmarIthawi** [python-social-auth/social-core#157]
There's Azure service called [AD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/https://azure.microsoft.com/en-us/services/active-directory-b2c/) for IAM. The differences between Azure AD and Azure AD B2C are different API endpoints and request/response parameters. Therefore there's a necessity to develop new backend for this service.

Functionality to be developed is common: login, sign up, logout and token refresh.

This issue is a copy of https://github.com/python-social-auth/social-app-django/issues/61 but I think this is the correct repo for it.

**Comment by OmarIthawi** [comment]
@InfiniteLegend @omab FYI I'm planning to work on this in the near future. I will keep you posted.

**Comment by InfiniteLegend** [comment]
Sure. I implemented B2C backend for one project and was about to clean-up everything and contribute, but didn't have enough time to do that. If you want, I can share gists with you. Hope it will help :)

**Comment by OmarIthawi** [comment]
That's great @InfiniteLegend! Please go ahead and add it here!

**Comment by InfiniteLegend** [comment]
Sure. Here is backend itself: https://gist.github.com/InfiniteLegend/0c11e44f2dd4cc688372c3b4a5c3c440 

Note that it was created for Django, therefore I take tenant_id, client_secret and client_id from settings (which is not good, but was enough for test purposes). In case of writing pure backend that doesn't depend on Django, you've to think about better solution

Here is middleware for Django. I hope it will also help you :) https://gist.github.com/InfiniteLegend/f715f26883ce9947ab57344f2239cd63

**Comment by OmarIthawi** [comment]
Thanks a million for your contribution @InfiniteLegend. It would help me a lot if you add this license both of your gists:

 - https://github.com/python-social-auth/social-core/blob/master/LICENSE

This will ease out all the legal issue for me and for the project.

**Comment by InfiniteLegend** [comment]
@OmarIthawi, done. I am glad that my drafts can help you)

**Comment by OmarIthawi** [comment]
@InfiniteLegend it's a bit confusing. I looked up everywhere, but couldn't reason about the existing [`azuread_tenant`](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/azuread_tenant.py) backend.

Isn't that the B2C backend? If not then it must be the AzureAD B2B backend, no?

**Comment by OmarIthawi** [comment]
Just as an update, I'm working on the backend. I was delayed a bit by other work.

**Comment by OmarIthawi** [comment]
@InfiniteLegend it looks like AzureADTenant is what we need! So far it's working just fine for my purposes!

**Comment by OmarIthawi** [comment]
Hey @InfiniteLegend I've created a draft for the backend. Took me ages to get it done with proper signing and checks:

 - https://github.com/appsembler/python-social-auth/pull/5
