### ISSUE TITLE
Is it possible to use multiple accounts of the same type?

### ISSUE THREAD

**Issue by syabro** [python-social-auth/social-core#16]
We're working on social network post tool and user sometimes want to add a single  post to the multiple facebook accounts f.e.
So he must to sign to all of them first.
Does python social auth allow to do it?

**Comment by omab** [comment]
This libs just handles authentication/authorization, it doesn't post anything into facebook accounts, that's up to the project where it's used, but this lib does support multiple facebook accounts associated to a single user, but I guess you will need long-lived tokens for that to ensure that you can post to them without forcing a re-login on each one.

**Comment by omab** [comment]
This link could be usefult https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extensio
