### ISSUE TITLE
Dynamic values for backend settings

### ISSUE THREAD

**Issue by Alexx-G** [python-social-auth/social-core#172]
Is it possible to set dynamically values (e.g. via callables) for backend's settings?

E.g. I want to keep `SOCIAL_AUTH_FACEBOOK_SECRET` in DB (or encrypted) and get it whenever I need.
If there's no such feature, it would be helpful to set a callable for settings instead of the actual value.

I guess it's possible to override DjangoStrategy, but maybe it's already implemented...

**Comment by omab** [comment]
@Alexx-G, there's no such feature built-in, the best approach is the one you mention, override the strategy and add the extra bits to call the callable.
