### ISSUE TITLE
500 Error in LinkedIn Oauth2 Workflow

### ISSUE THREAD

**Issue by alexmbird** [python-social-auth/social-core#173]
I'm trying to integrate python-social-auth into a Django site so users can login via LinkedIn.  I've followed the instructions (I hope correctly) and my app correctly sends the user off to LinkedIn to authorise the login.

Once authorised LinkedIn bounces the user back to `https://my-site/complete/linkedin-oauth2/?code=...`, and social-auth calls `https://api.linkedin.com/v1/people/~:(first-name,id,last-name)?format=json` to try and get some data for the user.

At this point LinkedIn returns a 500 error.  social-auth throws the exception `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.linkedin.com/v1/people/~:(first-name,id,last-name)?format=json`.

I've tried dialing up the logging on social/requests/httplib to DEBUG so all the headers are printed, and while I'm no oauth expert they look appropriate.  I wonder if this is a bug at LinkedIn's end but I'm hesitant to file a report until I know others are running into the same thing.

I'm running:
```bash
$ pip freeze | grep social
python-social-auth==0.3.6
social-auth-app-django==2.1.0
social-auth-core==1.6.0
```

**Comment by eoinof** [comment]
I'm investigating the same issue at the moment..

**Comment by ksuhaster** [comment]
I have the same problem, same versions
on my site problem started 4 days ago January 5 2018 00:47:51 UTC
before that all that were working for 4 monthes or so

**Comment by ksuhaster** [comment]
thank you, eoinof !
I've pinned social-auth-core==1.5.0 and it works

when I "didn't change anything", I rebuilt docker container and they have in
social-app-django/requirements.txt
social-auth-core >= 1.2.0
so I've got 1.6.0 after having 1.5.0 and that broke linkedin

**Comment by ksuhaster** [comment]
https://github.com/python-social-auth/social-core/pull/165
this pull request actually broke linkedin
if revert only this changes, 1.6.0 also works

**Comment by browniebroke** [comment]
I've tried to play around the version from the above pull request in my project using social-auth-core, and it seems to work. 
Thank you @bisby for finding the solution.
