### ISSUE TITLE
Wrong settings key for Azure AD Tenant SOCIAL_AUTH_AZUREAD_OAUTH2_KEY

### ISSUE THREAD

**Issue by chitak** [python-social-auth/social-core#187]
Hi,

I am receiving error "Invalid audience" while doing integration to Azure AD.

After some dig into the code, I think the audience should be getting from SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY instead of SOCIAL_AUTH_AZUREAD_OAUTH2_KEY.

https://github.com/python-social-auth/social-core/blob/a7b3f368e63bc17723d0956cebad15726d1e31ab/social_core/backends/azuread_tenant.py#L112

I can fix this and create pull request if needed.

Thanks

**Comment by OmarIthawi** [comment]
Please do @chitak!

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/fb7eabd318b6839ce5cb6329b2ca77205f21a493
