### ISSUE TITLE
Add Telegram auth backend

### ISSUE THREAD

**Issue by adilkhash** [python-social-auth/social-core#206]
Hey guys!

Recently Telegram announced [Telegram Login Widget](https://core.telegram.org/widgets/login) and I decided  to add Telegram backend  to social-auth.
Here is PR: #205

**Comment by Hecsall** [comment]
Are there any plan to merge this PR?
I just started using python social auth and i could need the telegram login.
Good work btw!

**Comment by adilkhash** [comment]
@Hecsall if you want to use Telegram backend you can use my fork, master branch. I do use it already.

**Comment by vitaliyharchenko** [comment]
Waiting for this great feature to merge! @omab

**Comment by omab** [comment]
PR #205 merged. Thanks!

**Comment by Sashkow** [comment]
The fork seems to be merged but when I `pip install python-social-auth' and add `'social_core.backends.telegram.TelegramAuth'` to a list of `AUTHENTICATION_BACKENDS` I get
ImportError: No module named 'social_core.backends.telegram'. How to use latest version of this repository in my project?

**Comment by adilkhash** [comment]
@Sashkow because release is not ready, currently you can do this:

`pip install https://github.com/python-social-auth/social-core/archive/master.zip`

**Comment by erayerdin** [comment]
Hi,

I haven't seen Telegram on the list in [documentation](https://python-social-auth.readthedocs.io/en/latest/intro.html#features), so I've wanted to ask. Is the release ready (and somehow not present in docs)?

**Comment by mediabots** [comment]
+1 @erayerdin
Yes
I am also waiting for DOCS for Telegram
