### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by camilonova** [python-social-auth/social-core#218]
I have at the middleware:

`'social_django.middleware.SocialAuthExceptionMiddleware'`

And I have this setting:

`WHITELISTED_DOMAINS = ['example.com']`

When I try to login with a gmail account I get a server error:

`[ERROR] AuthForbidden: Your credentials aren't allowed `

I don't expect to get a server error, because I use the middleware. What I'm I missing here?

**Comment by omab** [comment]
If you have `debug` mode activated, then the exception will raise anyway, this proved to be useful to debug wile developing.

**Comment by felipe3dfx** [comment]
No, it doesn't work using the following settings:
```
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
DEBUG = False
```
