### ISSUE TITLE
How to associate user with username and email?

### ISSUE THREAD

**Issue by muthuhari** [python-social-auth/social-core#226]
I have a website where users can log in with username and password, now I want to implement google login. so, i am planning to use social-auth-app-django, and I want to use sub field return by google as username, but the problem is when the user login using google, I want to update old users username also, so what is the best way to achieve this?

for example: let's say the user john has username: John and email is john@domain.com, now if he login using his google account I want to update his username as sub field like 1076915035xxxxxxxxxx

Problem: Since the website is for an organization, there are chances for same Gmail(GSuite) account for users with the different time period. like if John leaves an organization another user whose name is John can get the new Gmail account with the same name.

Now I am implementing following methods.
`
    

     def social_uid(backend, details, response, *args, **kwargs):
            return { 'uid': response.get("id") }

    def get_username(strategy, details, response, backend, user=None, *args, **kwargs):
        sub = response.get("id")
        return { "username" : sub }

    def associate_by_email_sub(backend, details, response, user=None, *args, **kwargs):
        email = details.get("email")
        username = response.get("id")

        if email and username:
            users = list(User.objects.filter(email=email, username=username))
            if len(users) == 0:
                return {  'user' : None, 'is_new' : True }
            elif len(users) > 1:
                raise AuthException(
                    backend,
                    'The given email address is associated with another account'
                )
            else:
                return { 'user' : users[0], 'is_new' : False }
`

i want to know above approach is safe?

**Comment by omab** [comment]
If the new incoming user is not reusing the original account (as in, the ID in google changes), then the approach seems safe enough to me.
