### ISSUE TITLE
List of providers for services that shut down

### ISSUE THREAD

**Issue by rafalp** [python-social-auth/social-core#231]
I've took a time to go trough each provider that exists and see which ones are gone:

- `appsfuel` - appsfuel.com returns 404, all internet activity cuts off in 2014
- `beats` - beatsmusic.com shut down late 2015
- `changetip` - changetip.com shut down late 2016
- `clef` - clef.io shut down in 1Q of 2017
- `mindeid` - mineid.org seems down as of time of this writing
- `persona` - Persona is no longer maintained by the Mozilla and was moved to community for maintenance, browserid.org returns 404
- ~~`pixelpin` - pixelpin.co.uk times out, no current google results suggesting that service is maintained any longer~~ moved to `pixelpin.io`
- `rdio` - Rdio was bought out by Pandora in mid 2015, API endpoints are redirecting me to "Pandora is not available in your country... YET!" so I'm unable to see if their oauth api is gone
- `readability` - Readability shut down in september 2016
- `thisismyjam` - Shut down in middle of 2015

**Comment by rafalp** [comment]
Allright, I've crossed you guys off the list!

**Comment by omab** [comment]
@rafalp this is an awesome list, I'll proceed and get rid of the ones that are dead now. Many thanks!
