### ISSUE TITLE
For some reason google oauth2 can signup into same user with different gmail emails

### ISSUE THREAD

**Issue by imomaliev** [python-social-auth/social-core#232]
Sometimes when user signups with his gmail account to my service and then he signups with his G Suite account, both emails create record in UserSocialAuth model but to same django User. Can someone help me understand why this happens and how to avoid it? I need both gmail accounts have separate django accounts.

```python
SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',

    # request consent if no refresh_token
    'contrib.pipelines.redirect_if_no_refresh_token',

    'social_core.pipeline.user.get_username',
    # http://python-social-auth.readthedocs.io/en/latest/use_cases.html#associate-users-by-email
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',

    'contrib.pipelines.get_avatar',
    # create default data for user
    'contrib.pipelines.dummy_data.create',
]
```
Here is how it looks in my db
```python
In [7]: for uu in UserSocialAuth.objects.filter(user__email='me@mydomain.com').values():
   ...:     print(uu)
   ...:
{'user_id': 133, 'uid': 'me@mydomain.com', 'provider': 'google-oauth2', 'id': 125, 'extra_data': {'auth_time': 1523347209, 'access_token': '...', 'expires': 3600, 'token_type': 'Bearer', 'refresh_token': '...'}}
{'user_id': 133, 'uid': 'me@gmail.com', 'provider': 'google-oauth2', 'id': 401, 'extra_data': {'auth_time': 1522379769, 'access_token': '...', 'expires': 3598, 'token_type': 'Bearer'}}
```

**Comment by imomaliev** [comment]
@omab bump?

**Comment by omab** [comment]
@imomaliev, if the user doesn't logout from your app, and then proceeds to login with the second GSuit account, then the new social account is associated to the currently logged in user. If you want to enforce separated accounts, then you need to force that no user is currently logged in in your site.

**Comment by imomaliev** [comment]
@omab May be we should add `LOGOUT_ON_LOGIN` setting to social_django, if `True` then `auth` view will logout current user before starting login?

**Comment by omab** [comment]
@imomaliev, if that's implemented, it needs to take into account all the frameworks implemented, logging and user in and out depends on the framework it runs on, and even then, it can depend on third-party dependencies.

**Comment by imomaliev** [comment]
@omab You mean we can't just implement this only in `social_django`?

**Comment by omab** [comment]
@imomaliev, yes, it can be implemented on a single framework, but for these kind of features that have such impact on the user experience, I prefer to have them implemented on each supported framework, or at least have the corresponding placeholders in the codebase for them to be implemented at some point or for the developer to extend with the desired functionality.
