### ISSUE TITLE
Get state before login (oauth)

### ISSUE THREAD

**Issue by guillenotfound** [python-social-auth/social-core#237]
Is there a way to get `state` for Google provider before login without creating a custom provider and overriding that method? 

Another option would be to substitute it via query parameter but seems like the code actually ignores it.

**Comment by omab** [comment]
What do you mean with `get state`?

**Comment by ZiFFeL1992** [comment]
`state` can be passed as a query param, in some cases as CSRF and in some others as an identifier to match someone before doing oauth and after doing it.

In my case I use Google Oauth 2, if I pass `state` to login:

`mydomain.com/login/?state=randomString`

I hope that the response in the callback request contains an `?state=randomString`.

But [this method](https://github.com/python-social-auth/social-core/blob/2313aa29b49dfbdcca3a2d8601161f23c4d1bae8/social_core/backends/oauth.py#L54) forces the library to create it's own state (and ignores if I explicitly pass one) for each user which is fine for 99% of cases but is not when you want to identify an user before and after login for tracking purposes (for example).

**Comment by omab** [comment]
A problem I see is that `state` is a reserved parameter for OAuth, it's purpose is to serve as a CSRF verification token to ensure that the request was generated from the same server, if you have your own `state` parameter, it will be replaced with the one needed to ensure the service security.

Another problem, is that not all the providers will accept extra parameters in the redirect URLs, or they might accept them, but not return them, so I wouldn't rely on this to get custom parameters back.

**Comment by ZiFFeL1992** [comment]
Okey so is there any away to retrieve `state` after login? I can get it from pipeline, but in subsequent requests?

Thanks!

**Comment by omab** [comment]
The problem with the pipeline, is that it's executed after the provider redirects back to your site, at that point your parameter will be gone. What you can use is the `SOCIAL_AUTH_FIELDS_STORED_IN_SESSION` setting, it's a list of parameters names which must be stored in the session, you can access them from there later in the auth process.

This [doc](https://python-social-auth.readthedocs.io/en/latest/developer_intro.html?highlight=FIELDS_STORED_IN_SESSION#interrupting-the-pipeline-and-communicating-with-views) can server as guideline.
