### ISSUE TITLE
[query] Is there a drop-in replacement for django_openid_auth.models.UserOpenID?

### ISSUE THREAD

**Issue by david-libremone** [python-social-auth/social-core#238]
I'm planning on migrating from `django_openid_auth` to `python-social-auth`. I currently use the `UserOpenID` class from `django_openid_auth`. Is there a drop-in replacement in the new library, perhaps `social_core.backends.open_id.OpenIdAuth`?

(This is for generic OpenID authentication, not provider-specific.)

**Comment by omab** [comment]
As you pointed out, there's the generic [OpenId](https://github.com/python-social-auth/social-core/commit/a483c7e45b90e545c347b885b4553297e4d0b613) provider, but I'm not familiar with `django_openid_auth` internals to be completely sure if it's a right substitution.

**Comment by kwill** [comment]
A quick point of confirmation: we are talking about OpenID 2.0 not OpenID Connect?
