### ISSUE TITLE
twitter login requires valid callback url

### ISSUE THREAD

**Issue by tisdall** [python-social-auth/social-core#249]
I found in the [twitter docs](https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token):

> Starting June 12th, 2018, we will require that any callback URL used with this endpoint will have to be whitelisted within the app settings on apps.twitter.com

The [python-social-auth docs](http://python-social-auth-docs.readthedocs.io/en/latest/backends/twitter.html) currently say:

> You need to specify an URL callback or the application will be marked as Client type instead of the Browser. Almost any dummy value will work if you plan some test.

The docs should say that the callback must be set to the correct URL or it will raise a "403 Client Error" and that the URL should be something like "https://example.com/complete/twitter/"

**Comment by RAJKUMAR18** [comment]
So can you elaborate as to what should be the case when developing on localhost
I provided http://localhost:8000/accounts/twitter as callback raising 403 error Is there some guide docs etc

**Comment by tisdall** [comment]
I'm using "http://example.com:8000/complete/twitter/" as my callback URL for my local development and that's working fine.  I have in my /etc/hosts an entry saying `127.0.0.1  example.com`.  "localhost" should work unless they're specifically restricted that.

Oh..  you have `accounts` in your URL instead of `complete`, is that the issue?

**Comment by RAJKUMAR18** [comment]
I used django-allauth whose callback is different.
But I solved it i was misconfigured in my admin settings.
Thanks.

**Comment by stanicaa** [comment]
I had the same issue ... in my case, I added BOTH links to the callbacks (with and without 'www') after https://
It basically depends on how you set up your server (what links it serves), and then make sure you set up all the relevant links with Twitter too.
