### ISSUE TITLE
Unable to select a specific region for Battle.net oAuth

### ISSUE THREAD

**Issue by greatman** [python-social-auth/social-core#256]
The current implementation of the Battle.NET oAuth only handle users in the EU region.

This causes issues when we want to gather character information for a player in another region. The Blizzard API just returns the specific characters in a region.

There are 4 total regions in the Battle.NET api: US, EU, TW, KR

A fix could be to just have a variable. Something like SOCIAL_AUTH_BATTLENET_REGION which we would set to one of the 4 regions.

**Comment by riklaunim** [comment]
hm... isn't account global while services like a game license region specific? WoW stuff is for sure. User info should return in which regions which user services are used. (or other discovery option).
