### ISSUE TITLE
Problem with Instagram authentication if user is not logged to instagram beforehand

### ISSUE THREAD

**Issue by riklaunim** [python-social-auth/social-core#260]
I have a weird problem with Instagram OAuth in two apps - one using latest and one bit old python-social-auth. If a user tries to login with Instagram then subsequent access_token request will fail:

```400 Client Error: Bad Request for url: https://api.instagram.com/oauth/access_token```

but only if the user isn't logged in to Instagram beforehand. If you login to instagram while in the process of oauth login it fails, but if you try again it passes. If you login to instagram beforehand and try it passes.

Anyone noticed this behavior?

**Comment by jgoclawski** [comment]
What seems to help is setting `REDIRECT_STATE = False` for Instagram backend. There's something weird going on with Instagram as it sometimes passes "redirect_state" parameter and sometimes it does not. "state" and "code" parameters are always passed correctly.

```
from social.backends import instagram
class InstagramAuth(instagram.InstagramOAuth2):
    REDIRECT_STATE = False
```

@omab Should this fix be commited as a PR or does it have any side effects I'm not aware of?

**Comment by gnalbandian** [comment]
same problem here:

/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.instagram.com/oauth/access_token


This error only happens while navigating with a computer. If I set developer mode in chrome, as if I was using an iphone, the issue is gone.

**Comment by EralpB** [comment]
This issue is pretty huge, what is the solution? Happens 100%.

**Comment by mannemvamsi** [comment]
I used 
`from social_core.backends import instagram` from @jgoclawski 's answer.

**Comment by theoden-dd** [comment]
Well, it's not stale, it's still actual. Please note that just recently the flow didn't work for me without the same fix: https://github.com/sunscrapers/djoser/issues/403#issuecomment-1112573482
