### ISSUE TITLE
Return sucess with partial pipelines

### ISSUE THREAD

**Issue by rammanoj** [python-social-auth/social-core#262]
I actually used this app in oauth. I defined my own pipeline to save data to the user and UserSocailAuth model. After saving the details successfully how actually the value has to be returned so that successful login happens ??

My pipelines list:

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'userauth.social_get_pipeline.get_user',
    'userauth.social_save_user.savedata',
)
@omab  Is there any way to return success so that the page will be redirected to LOGIN_REDIRECT_URL ??

**Comment by omab** [comment]
@rammanoj, the most important bit of the pipeline return is the `user` instance, it should be a key in the return `dict` like `{'user': user}`, this user must have the `is_active` flag set to `True` in order to consider it a valid candidate for `login`. Another useful bit is the `is_new` flag which marks if the user is new or not.

**Comment by rammanoj** [comment]
thanks for reply @omab I don't want the user to signup using OAuth and I defaulty configured is_active to false for every user. So, whenever admin makes the user active, the user can log in(with OAuth even). I am saving the details to user table and UserSocialAuth table and then using login function to login (But I am unable to it as I don't have request parameter). So, I want to return success if the user is registered and already active. So, is there any way to do it ??

This is my code in the social_save_user pipeline

from social_core.pipeline.user import get_username
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse
from social_django.models import UserSocialAuth
from django.contrib.auth import login
import json, requests
import warnings
# if user exists and active, then if user also has social account saved
# then login to return nothing, else return parameters to save the user
# social account
def get_user(strategy, details, user=None, *args, **kwargs):
    result = get_username(strategy, details, user=user, *args, **kwargs)
    print(kwargs['uid'])
    try:
        user = User.objects.get(email=details['email'])
    except User.DoesNotExist:
        user = None
    if User.objects.filter(email=details['email']).exists():
        print(user)
        if user.is_active:
            #store other detials to usersocialauth table(for first time)
            print(kwargs)
            provider = 'github'
            extra_data = {}
            extra_data['token_type'] = '# get token type from details'
            extra_data['expires'] = '# get expiry status'
            extra_data['access_token'] = '# get access token'
            extra_data['id'] = '#get id'
            oauth = UserSocialAuth.objects.all()
            for i in oauth:
                if i.pk == user.pk and i.provider == provider:
                    value = i
                    break
                else:
                    value = None
            #save details if provider doesnot exist
            # if value == None:
            #     social_login = UserSocialAuth.create(
            #     user=user.pk,Uid=kwargs['uid'],
            #     Provider= provider, ExtraData=extra_data)
            #     solial_login.save()
            # elif value != None:
            social_login = UserSocialAuth(
            user=user,uid=kwargs['uid'],
            provider= provider, extra_data=extra_data).save()
            print('enterning user')
           # need to login here or return success so that user can login
            client = requests.session()
            client.get('https://127.0.0.1:8000/userauth/login')
            csrftoken = client.cookies['csrftoken']
            data = { 'username': user.username, 'password': user.password}
            r1=client.post('https://127.0.0.1:8000/userauth/login',data=data)
            #login(s, user)
            return redirect('/music/list')
        else:
            # if user is not yet accepted wait till his his accpetance
            return HttpResponse("<h1>Your registration is still under progress</h1>")
    else:
        # if user has not registered, request him for registration
        return redirect('/userauth/signup')

So, Is there any way to login on success?

**Comment by rammanoj** [comment]
default

**Comment by rammanoj** [comment]
@omab can you please specify how to prevent multiple social accounts based on the email of the user ??

**Comment by rammanoj** [comment]
Thanks for reply @omab I figured out how to solve this. This is really a simple package. I referred to the documentation and changed the order of pipelines and it worked fine.
