### ISSUE TITLE
'list' object has no attribute 'strip' , issues in social_core.pipeline.user.create_user 

### ISSUE THREAD

**Issue by mingderekwang** [python-social-auth/social-core#264]
Django Version: | 2.0.7
-- | --
AttributeError
'list' object has no attribute 'strip'
   def normalize_email(cls, email):
        """
        Normalize the email address by lowercasing the domain part of it.
        """
        email = email or ''
        try:
            email_name, domain_part = email.strip().rsplit('@', 1) ...
        except ValueError:
            pass
        else:
            email = email_name + '@' + domain_part.lower()
        return email

when the identity provider return the email address as a array, during the social_core.pipeline.user.create_user, it will throw this error

**Comment by omab** [comment]
Which backend and steps to reproduce it?

**Comment by mingderekwang** [comment]
azuread_b2c, just implement as example and when the B2C return the email as array, the issue occur.

**Comment by omab** [comment]
Could you check fede252 if that fixes the error?

**Comment by omab** [comment]
@mingderekwang, that revision is actually broken, here's the fixed one: 545a376
