### ISSUE TITLE
Disfunctional telegram backend

### ISSUE THREAD

**Issue by ei-grad** [python-social-auth/social-core#265]
In #206 @adilkhash says that he is using this backend, but I don't understand how it could be possible, because the backend implementation lacks the `auth_url()` method, which is required.

@adilkhash @omab could you guys provide any clue in case if I'm missing something?

Btw, is there any kind of smoke-testing for all backends to catch such things?

**Comment by omab** [comment]
@ei-grad, AFAIK the `telegram` backend is supposed to be used with the `Telegram Login Widget`, this docs might help https://core.telegram.org/widgets/login.

**Comment by omab** [comment]
BTW, there are no smoke tests to validate this kind of stuff against the real APIs.

**Comment by ei-grad** [comment]
Oh, am I understand right that it is supposed just to be used with the "complete" PSA step? Ok, looks working. Thanks. Sorry for inconvinience.

**Comment by adilkhash** [comment]
@ei-grad take a look at the article https://khashtamov.com/ru/telegram-auth-django/ and repo https://github.com/adilkhash/django-telegram-auth-example
