### ISSUE TITLE
New release 1.7.1 or 1.8.0

### ISSUE THREAD

**Issue by aleksihakli** [python-social-auth/social-core#266]
Hello,

would it be possible to bake a new release for `social-auth-core`? There are some pieces of code in the current master that are unreleased and would be nice to have on PyPI.

Thank you in advance!

**Comment by aleksihakli** [comment]
Hi @omab, would it be possible to bake a new release for this awesome package?

**Comment by omab** [comment]
@aleksihakli, package updated to `2.0.0`.

**Comment by omab** [comment]
j

**Comment by aleksihakli** [comment]
@omab Thanks, awesome!
