### ISSUE TITLE
SOCIAL_AUTH_FACEBOOK_SCOPE denied_scopes

### ISSUE THREAD

**Issue by secsd** [python-social-auth/social-core#277]
["user_birthday", "user_location", "user_events", "user_photos", "user_videos", "user_friends", "user_posts", "user_gender", "user_link", "user_age_range", "email", "publish_to_groups", "groups_access_member_info", "public_profile"], "denied_scopes": null,..

from my backend
how to make it granted?

**Comment by dmpe** [comment]
@secsd you need to go through app review process. just email &username is free by default; with version 3.1
