### ISSUE TITLE
Upgrade facebook from 2.9 to 3.2

### ISSUE THREAD

**Issue by dmpe** [python-social-auth/social-core#279]
Hi, 
facebook has upgraded their login api to 3.1 which has brough quite some changes. 

The impacted backend:
https://github.com/python-social-auth/social-core/blob/master/social_core/backends/facebook.py

The website with changelog:
https://developers.facebook.com/docs/facebook-login/changelog

Major change is: **New scopes and `Additional Review Required for Certain Permissions`**
- [x] by default & without any app review, one can only access 3 fields: `name`, `email`, `profile_picture`

**Comment by dmpe** [comment]
Just to make it clear: It seems to work with the current version.

**Comment by tisdall** [comment]
In 3.0 it says they stop using `user_id`.  Doesn't that break things?

**Comment by tisdall** [comment]
I just tested it myself with 3.1 and it seems to be working correctly.  The `user_id` that's provided is already the "third party id" and not the Facebook one.  It no longer says `user_id` in the list of granted scopes, but I don't really understand how that affects things.

**Comment by tisdall** [comment]
Sorry... I should say I changed the API version setting in developers.facebook.com , but didn't change the `API_VERSION` in the code.  The code specifically calls the 2.9 endpoint, but the setting may upgrade it any way.

**Comment by dmpe** [comment]
Hi, 
That was quick :) , I was just preparing to post this as well. 
I have also changed the API version to 3.1 and that was basically it. 
....
as I understand from this [FB page](https://developers.facebook.com/docs/facebook-login/permissions/?locale=en_US#reference-default), `user_id` was replaced with `default` to encompass those former fields.
Being a novice with Django and social login in general, for my app [b40re.tk](b40re.tk) which I host on Heroku and where FB [login is currently being in the "implementation"](https://github.com/dmpe/django-wohn/tree/master/userMng), what I get from extra data

```
"{\"id\": \"529775064135899\", \"expires\": 5116611, \"auth_time\": 1537441045, \"token_type\": null, \"access_token\": \"EAAHdvx6PTlYBAMbdQa7VpZBZAG9mgwbu73eGNuZCzlFb2RCwNvFVgxQEi9DaGZCl5xwso6yG0KE2eCHUzBYHotto2YZCa595dtl1842pHEa7SQehjZAdfUAOGKAxfZArIZCACvXLGFiVKdXdQsbFeiLBuv0ZCVmQfoaCMHJY9U0sIvZAn1ZBqXxdv10\", \"denied_scopes\": null, \"granted_scopes\": [\"email\", \"public_profile\"]}"
```
At such, other than the API version upgrade I dont think, after all, that much is going to change.

**Comment by ibolit** [comment]
Hi. 

With facebook dropping support for api v2.9 in April, what do we do as developers?
I can't just change the api version in the code as the library is downloaded each time during development.
I can wrap it in my own one, but it feels dirty.

**Comment by dmpe** [comment]
@ibolit @tisdall I could create PR ... Would there be an interest in reviewing it ?

**Comment by tisdall** [comment]
I believe they've already gone ahead with forcing a manual review on additional scopes so I don't thick that affects anything further.  I think it's just changing the `API_VERSION` and then testing it out.  There seems to be a 3.2 version out, though, so maybe it should be changed to the latest?

@dmpe - tag me in your PR and I'll take a look

**Comment by ibolit** [comment]
@

**Comment by dmpe** [comment]
> . There seems to be a 3.2 version out, though, so maybe it should be changed to the latest? tag me in your PR and I'll take a look

Will look over the weekend into this.
