### ISSUE TITLE
RFC: kerberos & LDAP backends

### ISSUE THREAD

**Issue by atodorov** [python-social-auth/social-core#296]
I am working on Kerberos and LDAP backends because we need them as options in Kiwi TCMS. If you are OK with merging them as part of the core package I will send a pull request. Otherwise I can bundle them as independent plugins.

**Comment by mikeengland** [comment]
👍 It would be good to see this as part of the core package IMO, as it is a pretty common authentication use case.

**Comment by atodorov** [comment]
@omab can you tell us why you'd closed this issue? 

It's definitely not stale, looks like there is interest in this feature and I can contribute my package back to upstream if you'd like to have it.

**Comment by mikeengland** [comment]
That sounds great @atodorov !

**Comment by maparent** [comment]
@atodorov Curious: You mention this issue in your repository with a Kerberos backend. I could not find any repository with a LDAP backend, though you mention it here. Did you already work on it? Thank you!

**Comment by atodorov** [comment]
> @atodorov Curious: You mention this issue in your repository with a Kerberos backend. I could not find any repository with a LDAP backend, though you mention it here. Did you already work on it? Thank you!

@maparent  - No. I worked on the Kerberos backend first and then for LDAP used django-ldap IIRC.

**Comment by maparent** [comment]
Ah, well. Thank you for the prompt reply!
