### ISSUE TITLE
username from uuid4().hex results in TypeError

### ISSUE THREAD

**Issue by tuky** [python-social-auth/social-core#3]
The fallback https://github.com/python-social-auth/social-core/blob/master/social_core/pipeline/user.py#L40 generates a `str` in python 2.7. This later raises a `TypeError` when calling `unicodedata.normalize('NFKD', value)` in the contributed `slugify`.

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/e2e3a25561068809421bad9360f9fd5885fcd492.

Thanks!
