### ISSUE TITLE
Google+ Starts Going Away in January 2019

### ISSUE THREAD

**Issue by pizzapanther** [python-social-auth/social-core#300]
I think this URL needs to change: https://github.com/python-social-auth/social-core/blob/master/social_core/backends/google.py#L56

From Google:

*On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.*

**Comment by pizzapanther** [comment]
I think this is the URL that needs to be used instead: `https://www.googleapis.com/oauth2/v2/userinfo`

**Comment by pizzapanther** [comment]
or `https://www.googleapis.com/userinfo/v2/me`

**Comment by codingjoe** [comment]
Same here, we just got the warning from google. I would also recommend to remove the Google+ backends in the next release. This way users get yet another warning, that they will be deprecated soon. Very soon in fact.

**Comment by marc-gist** [comment]
thanks @pizzapanther hopefully this makes it into the pip repository asap :)

**Comment by pizzapanther** [comment]
I have a PR coming with just the URL change. Testing now. I figured the other Google+ removal should come later since you can still use it if you really want to until March.

**Comment by tisdall** [comment]
Someone just submitted #301...  maybe you should collaborate, @pizzapanther

**Comment by omab** [comment]
PR #301 merged.

**Comment by omab** [comment]
Also, `v3.0.0` released with the changes.

**Comment by Tiagojdferreira** [comment]
I just started looking at the issue of deprecation of the api and I have some questions regarding the migration process.
I see that the GooglePlusAuth class extends the BaseGoogleOAuth2API (fixing the url), but I also see it still asks for [the scopes `plus.me` and `plus.login` which should be replaced by `profile` and `openid`.](https://developers.google.com/identity/sign-in/web/quick-migration-guide).

Are you completely dropping support for the class GooglePlusAuth and I should start using GoogleOAuth2?

**Comment by tisdall** [comment]
@Tiagojdferreira - There's 2 different classes, `GoogleOAuth2` and `GooglePlusAuth`.  The #301 PR fixes the `GoogleOAuth2` one so it no longer has any connection to Google+ and will continue to work after the shutdown.  The `GooglePlusAuth` continues to use the Google+ API's and will eventually stop working when Google shuts it down.

If you were already using `GoogleOAuth2` then upgrading to the v3.0.0 version will be all that's needed to "migrate".  If you're using `GooglePlusAuth` then you should change it to `GoogleOAuth2` before Google shuts down the API calls.

**Comment by ckang5190** [comment]
@tisdall I'm only using GoogleOAuth2, have upgraded to 3.0.0, but when I test my login I still see "https://www.googleapis.com/auth/plus.me" under the GET request's "scope". Any help?

**Comment by tisdall** [comment]
@ckang5190 - Where are you seeing that?  That scope is only defined within `GooglePlusAuth`.  If you're using Django, double check what all is in your `AUTHENTICATION_BACKENDS` settings.

**Comment by ckang5190** [comment]
@tisdall here's my AUTHENTICATION_BACKENDS:

**AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'django_auth_ldap.backend.LDAPBackend'
)**

I have a backup login method via LDAP, but I doubt that affects this.

My GET request for OAuth2 completion is as follows: 

**[24/Jan/2019 11:55:13] "GET /auth/complete/google-oauth2/?state=[redacted]&code=[redacted]&scope=openid%20email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/plus.me%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=[redacted]&session_state=[redacted]&prompt=none HTTP/1.1" 302 0**

My pip freeze shows **social-auth-core==3.0.0** for sure. This was replicated in a couple of different environments where there was s**ocial-auth-app-django=2.1.0/3.1.0**, and **python-social-auth==0.3.6/not installed**. 

Could it be I'm missing/need to upgrade any packages? Please advise.

**Comment by tisdall** [comment]
@ckang5190 - Hmm..  I see that now too.  But I think that's coming from Google.  The request sent to Google says `https://accounts.google.com/o/oauth2/auth?scope=openid+email+profile&state= ...` and then after the authentication it redirects the user to the URL you've given.  You'll notice it has both the `openid%20email%20profile` scope we asked for and also the `plus.me` part, so maybe for compatibility it returns both?  I think it's safe to ignore it.

**Comment by ckang5190** [comment]
@tisdall right, I've also opened a support case w/ Google as well. Their page for creating OAuth2 Client key/secret pair doesn't allow the user to remove the "openid" from those 3 scopes, consistent w/ the GET request. 

Here's a screenshot of where that is:
![screen shot 2019-01-15 at 4 54 41 pm](https://user-images.githubusercontent.com/12374719/51765471-b1ae2100-208c-11e9-8130-af265ff183fc.png)

**Comment by ckang5190** [comment]
Just wondering if anyone else is running into the same issue w/ Google Cloud Console while also employing Python Social Auth like me. Please chime in and help if you can.

**Comment by tisdall** [comment]
I think the "openid" might be the base scope required for authentication and that's why it can't be removed...  but that's just me guessing. `GoogleOAuth2` defaults to asking for those 3 scopes, so I'd leave it as-is.

**Comment by gnud** [comment]
Do I need requestIdToken or requestServerAuthCode on Android to pass to Python?

I updated the social-auth package up to 3.0.0 and enabled 'social_core.backends.google.GoogleOAuth2'.

I use backend type: google-oauth2 and pass token, I tried both tokens and get as response:
`
{
  "error": "access_denied",
  "error_description": "Your credentials aren't allowed"
}
`

When I try manually to send a request to https://www.googleapis.com/oauth2/v3/userinfo, I get the same response, I read the docs on Google's api, says no header Authentication option, am I doing something wrong?

requestIdToken form:
`eyJhbGciOiJSUzI1NiIsIvbgZCI6ImYyNGQ2YTE5MzA2....`

requestServerAuthCode form:
`4/_ABNHi1dizr0GuBaw7vbiDNPXgu6YV1V3OCrQuHlSdkmWAH3grTsa8pZoRouO6z-tjD--OTri0SDQyd-gfgfggh`

**Comment by balsdorf** [comment]
If you are using the GoogleOpenIDConnect backend, it still uses a deprecated URL.

I've fixed this in fa373cd2b578f59be4b35043304d23af6591d6f8 but need to do some more testing before I make a PR.

**Comment by tisdall** [comment]
@balsdorf ... how?  I'm confused.  That's a link to a commit on the main repo, but the commit isn't actually there...  or something.  :)  I'm used to seeing a commit on a fork and then a PR is made.  What exactly did you do?

**Comment by balsdorf** [comment]
@tisdall Uh, thats some odd github behavior. I made the commit in my fork (https://github.com/balsdorf/social-core/commit/fa373cd2b578f59be4b35043304d23af6591d6f8) but when you click the link to the hash it is showing it in the main repo (which I don't have write access to).

I haven't made a PR yet as I need to make sure I follow the contributing guidelines but I wanted to get this out there if anyone was running into a similar issue.

**Comment by tisdall** [comment]
@balsdorf - I thought maybe you were some sort of wizard.  ^_^

I think what you have is fine.  Add something to the CHANGELOG, though.  Also, review the docs and make sure nothing needs altering there.  A PR will be more visible then this closed issue.
