### ISSUE TITLE
expires is stored as null in UserSocialAuth model's extra_param

### ISSUE THREAD

**Issue by awachat** [python-social-auth/social-core#31]
Instead of checking value of **expires_in** key for capturing the value of **expired** in UserSocialAuth model's extra_param attribute, [**expires** key is checked in response dict](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension) and [_null_ value is stored against **expires** in UserSocialAuth model's extra_param auth](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/facebook.py#L149).

[response](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/facebook.py#L94
)  = {
"access_token": <access_token>,
"expires_in" : <time_in_seconds>,
"token_type": "bearer"
}

Facebook API version 2.8 can be used to reproduce the error.
[Facebook API documentation](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension)

**Comment by omab** [comment]
Fixed by merged PR.
