### ISSUE TITLE
LinkedIn v1 deprecation

### ISSUE THREAD

**Issue by mpranjic** [python-social-auth/social-core#310]
https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context?trk=eml_mktg_gco_dev_api_comms

It seems linkedin backend is using v1 ([link](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/linkedin.py#L15))

**Comment by danielquinn** [comment]
The API will be [dropped](https://engineering.linkedin.com/blog/2018/12/developer-program-updates) as of March 1st (2weeks from now).

I'm looking into this for our own system, and if something useful comes out of it, I'll contribute it back, but it'd be good to know if anyone else is working on this.

**Comment by W3Technics** [comment]
I started implementing this, but I might need some help with the tests. They are kind of confusing me. Can I just open a pull request and let it be reviewed?

**Comment by W3Technics** [comment]
Getting a 'AuthFailed: Authentication failed: ('Connection aborted.', BadStatusLine("''",))' error on the tests, after getting the access_token, kind of lost. If any one could take a look and figure out what I'm doing wrong (probably something silly), that would be great!

**Comment by jaapdeheer** [comment]
@W3Technics I'm also trying to get this to work (as quickly as possible, with dirty hacks if need be), so if you get it working I'll be very interested! Of course I'll shout here if I have something working, though it probably won't be very fit for public consumption :)
Good luck!

**Comment by danielquinn** [comment]
[Here's what I have so far](https://gist.github.com/danielquinn/e5da6dc263a9e691a865932b16b64f3b).  It may be a decent starting point for someone trying to make something more generic.

**Comment by jaapdeheer** [comment]
@danielquinn you're a lifesaver! This seems to work perfectly for me.
Looks like I'll have time for sleep this weekend after all 😁 
Thanks a million to both @danielquinn & @W3Technics for sharing your hard work!

**Comment by jaapdeheer** [comment]
BTW I crudely removed the type hints to make it work in Python 3.4, my modified version is [here](https://gist.github.com/jaapdeheer/b58ee0d6ded142702f88c945c7dd3f78) in case it helps anyone.

**Comment by W3Technics** [comment]
I updated my code ([here](https://github.com/W3Technics/social-core/blob/feature/linkedin_api_v2/social_core/backends/linkedin_v2.py)) the code @jaapdeheer provided, and added support for retrieving profile pictures. I'm still testing this implementation.

**Comment by jaapdeheer** [comment]
Thanks  @W3Technics!
I updated my [gist](https://gist.github.com/jaapdeheer/b58ee0d6ded142702f88c945c7dd3f78) as well, adding rudimentary profile picture support inspired by your code. (Also I added back some type hints that I previously removed but that are actually supported fine by Python 3.4.)

**Comment by awachat** [comment]
I created a PR to support Linkedin Oauth2 with v2 API. 
https://github.com/python-social-auth/social-core/pull/322

**Comment by awachat** [comment]
I compiled a list of helpers that our app needed to get profile details once the access_token is retrieved.
Gist: https://gist.github.com/awachat/751bf6a354ea414eb48f85af9780b270. I hope someone will find this useful.
Thanks a ton to @danielquinn, @W3Technics & @jaapdeheer

**Comment by W3Technics** [comment]
Thanks, nice work! If this can be merged before friday, that would be great.

**Comment by Kashyap23** [comment]
@awachat I have made changes in my local machine by looking at your pull request, but I am getting error as 

**403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(firstName,id,lastName)**

Do i need to add anything else in settings.py ?

My settings :
```.json
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY=""
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET=""

AUTHENTICATION_BACKENDS = ( 
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'app.auth_backend.Auth0Backend'
)

SOCIAL_AUTH_PIPELINE = ( 
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'app.views.social_auth.process_login',
)
```

I have not added any `FIELD_SELECTORS`.Will that make any difference ?
I am running it on port to test it ( If that helps).
Please help me fix this issue. Thanks in advance.

**Comment by jaapdeheer** [comment]
@Kashyap23 maybe you are using `r_basicprofile` instead of `r_liteprofile` in `SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE`?
I think that can cause a 403 error, because `r_basicprofile` is no longer allowed with API v2.

**Comment by awachat** [comment]
@jaapdeheer  that's correct.
@Kashyap23  if the scope is not added explicitly then LinkedIn v2 implicitly assumes `r_basicprofile` scope and generates `acccess_token` for the same. 

Add the following in your settings.py to override the default scope.
```
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE=['r_liteprofile']
```

Hopefully, after March 1st, 2019; LinkedIn will update default implicit scope to `r_liteprofile`, if not, will need to add `DEFAULT_SCOPE` to `LinkedinOauth2` backend.

**Comment by awachat** [comment]
Without adding a scope, LinkedIn v2 API will throw 403 error. Retrieving `firstName` & `lastName` requires at least `r_liteprofile` scope. 

There is no simple way to remove the firstName and lastName from `LinkedinOauth2` backend. Unlike before Linkedin implicitly use  `r_basicprofile` as default scope, now Linkedin throws a 403 error if `r_liteprofile` is not added explicitly, it makes more sense to add the r_liteprofile as `DEFAULT_SCOPE`.

NOTE: if `emailAddress` is added to `FIELD_SELECTORS`, then `r_emailaddress` must be added to scope to avoid 403 error.

Thanks, @Kashyap23 @jaapdeheer

**Comment by danielquinn** [comment]
It's probably a good idea to include some compatibility checks against the scope values.  Something like:

```python
if "basic" in scopes:
    # issue warning
if "email" in fields:
        if "emailaddress" in scopes:
            # issue warning
```

**Comment by Kashyap23** [comment]
@jaapdeheer @awachat Thank you so much !! It Worked. 
Thanks Again.

**Comment by thomas-scrace** [comment]
What's the release status of this change? Is it included in the most recent release (3.1.0)?
Thanks!

**Comment by awachat** [comment]
@thomas-scrace for now, you may use this:
https://github.com/awachat/social-core/blob/upgrade/linkedin-v2/social_core/backends/linkedin.py

**Comment by thomas-scrace** [comment]
@awachat thanks. That's indeed what I'm doing :)

It seems like they haven't actually shut down the v1 API yet though.

**Comment by mpranjic** [comment]
Closing thanks to #322

**Comment by christianmtr** [comment]
I'm getting this:
`403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(email-address,firstName,id,lastName)`

With this settings:
```
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_emailaddress', 'r_liteprofile']
SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ['email-address']
```
Installed by : `pip install git+https://github.com/python-social-auth/social-core`

Do I need any other change/paremeter?

**Comment by awachat** [comment]
@christianmtr  try
```
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_liteprofile', 'r_emailaddress']
SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ['emailAddress']
```
**use emailAddress instead of email-address.**

If you remove the email address, does it throws the same error?
Also, from now you have to create a Product on the LinkedIn App and request for the email address and first_name, last_name permission. Login to the Linkedin developer website and check if the products are added successfully for the App.

**Comment by Kashyap23** [comment]
@awachat We recently updated our prod setups with the latest master of `social-auth-core`. We are facing the following error when trying to login with linkedin.
```
Authentication process canceled
```
The same is reported here https://github.com/python-social-auth/social-app-django/issues/182.
Can you please help us in the above ?

Thanks in advance!

**Comment by awachat** [comment]
Sure, @Kashyap23. Check my reply [here](https://github.com/python-social-auth/social-app-django/issues/182#issuecomment-496828593).

**Comment by awachat** [comment]
v3.2.0 is released to PyPi.
