### ISSUE TITLE
Google Plus deprecation

### ISSUE THREAD

**Issue by archatas** [python-social-auth/social-core#326]
[Google Plus is going to be shut down in a week.](https://venturebeat.com/2018/12/20/google-apis-to-close-down-on-march-7-2019/). Probably the documentation should mention how to migrate to a different Google Sign-in service.

**Comment by awachat** [comment]
If you are using `GoogleOAuth2` with the default scopes, all you need to is just to update the `social-core` package.

**Comment by balsdorf** [comment]
If you are using the GoogleOpenIDConnect backend, it still uses a deprecated URL.

I've fixed this in fa373cd2b578f59be4b35043304d23af6591d6f8 but need to do some more testing before I make a PR.
