### ISSUE TITLE
Add the ability to enforce 'team' restriction on Slack auth

### ISSUE THREAD

**Issue by Schwanksta** [python-social-auth/social-core#33]
Simple addition of a param to pass to the Slack auth URL.

**Comment by jeyraof** [comment]
Is this working?
When i use this feature in settings:

```python
SOCIAL_AUTH_SLACK_TEAM = 'slack-team-id like U1NEC967M'
```
another team was also permitted, and joined.

Can you give description for using this attribute?

**Comment by Schwanksta** [comment]
It depends. If you're signed in to Slack, using this should restrict your options to only the one team, which is useful. However, if the person isn't signed into slack, it will let them type in and authenticate with *any* team, which seems wrong to me, but it's how it works. 

I had to write a pipeline function and put it near the top to enforce teams on the server side:

`
def enforce_slack_team(user, response, backend, details, *args, **kwargs):
	if response['team']['id'] != settings.SOCIAL_AUTH_SLACK_TEAM:
		raise AuthForbidden(backend)`

This works for me on Django. Of course, I'm not sure if the current version of social_core in on pypi has my patch merged in.
