### ISSUE TITLE
CAS Auth

### ISSUE THREAD

**Issue by OvermindDL1** [python-social-auth/social-core#336]
Adding CAS support would be a great boon, old auth protocol, very similar to a more poorly designed OAuth2 and a lot easier to implement, but it's in heavy use in the educational industry in the USA for whatever reason.  There are a few python libraries that implement it that could be integrated into social-core, such as https://github.com/python-cas/python-cas, or it could be written from scratch, though it has such a large variety of implementations and formats that it would essentially be rewriting https://github.com/python-cas/python-cas anyway as it seems to have a whole lot of the weird corner issues (it's a very poorly defined protocol) already resolved.

**Comment by danizen** [comment]
+1 - I've been maintaining a package that leverages django-cas-ng, and now I need also to support some social login.  I'm likely to try this bug if no one else does, but first I need to make sure that I understand python-social-auth deeply enough.
