### ISSUE TITLE
long_description markdown not rendered correctly on PyPi

### ISSUE THREAD

**Issue by ryanwilsonperkin** [python-social-auth/social-core#342]
When viewing `social-core` [on PyPI](https://pypi.org/project/social-auth-core/) I noticed that the markdown is not being rendered correctly. There is an attribute that can be set in setuptools that will handle this.

**Comment by brainwane** [comment]
@omab Sorry, but [the Markdown is not being rendered correctly](https://pypi.org/project/social-auth-core/) right now. I think this issue needs reopening. You can use [this step-by-step troubleshooting guide](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/) to fix what's going wrong.

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/06b6d58dbabd47294047f83bebed467f91e0c9d5, released in `3.3.2`.
