### ISSUE TITLE
use 2 different sets of Twitter API keys in the same Django project

### ISSUE THREAD

**Issue by jeromecc** [python-social-auth/social-core#344]
Hi!
I am using python-social-auth successfully to sign in users with Twitter on my Django website. Thanks for the amazing work!
I searched and read the documentation carefully. I also searched online, but I couldn't find clear & recent advice about how to setup sign-in for 2 different Twitter  apps / accounts.
The use case is this: for basic features I will use the current Twitter app with minimal authorizations, so that users don't get scared away and don't feel like I could damage their privacy.

For advanced features, advanced users and "backend" features (like accessing the DMs of my own Twitter account), I would like to allow sign in with the maximum level of authorizations.

So I need two login urls (or rather with 2 different url parameters) for 2 different set of API keys.
The closest thing I found online is this: https://stackoverflow.com/questions/20089989/how-to-implement-signup-for-multiple-types-of-users-with-python-social-auth but it doesn't really help me and it's from 2013.
Could you please give me a hint? I can dive into the code if I have minimal guidance about where to start.
Thanks!!!
jérôme

**Comment by shaib** [comment]
Hi,
It probably doesn't help you anymore, but for anyone else running into this:

Inherit the Twitter backend, change its name and set whatever other attributes you like:
```python
class TwitterAdvanced(TwitterOAuth):
    """Twitter authentication backend for advanced users"""
    name = 'twitter_adv'
    DEFAULT_SCOPE = [...]  # or change scope via settings
```
Include this backend in your auth-backends, and that's it. You automatically get new settings for the keys and secrets and scopes and extra-data and what-have-you, plus a new URL for the login.
