### ISSUE TITLE
RFC: GitHub callback URL with django-tenants

### ISSUE THREAD

**Issue by atodorov** [python-social-auth/social-core#345]
We're using https://github.com/tomturner/django-tenants to build a multi-tenant add-on for https://github.com/kiwitcms/Kiwi. It just needs to be installed and hooked up into local_settings.py.

django-tenants uses PostgreSQL schemas and switching db.connection between them based on the hostname you are trying to access. This makes it possible for users to only see the data they have created. Which apps/tables are affected is controlled via settings, so called TENANT_APPS and SHARED_APPS.

In our case the "public" tenant is our demo website and SHARED_APPS=INSTALLED_APPS, including `social-auth-app-django` and `django.contrib.auth`.  They are not part of TENANT_APPS b/c we want to have accounts in a central place and then give some accounts access to their tenants with middleware. This means authorized accounts will share the same username/password between multiple tenants.

Question is how do I hook this with PSA, GitHub backend in particular. The 'Authorization callback URL' must be on the "public" tenant but how do we know where to redirect to ?

Also with user/pass login the same account needs to login separately into each tenant login url. I think this is because of session cookies.

Any ideas and pointers how to proceed in this scenario ?

**Comment by erikvlm** [comment]
Sorry to hijack, but how did you solve redirecting and logging the user in, to the tenant domain upon registration? Can't get sessions to work..

**Comment by atodorov** [comment]
SESSION_COOKIE_DOMAIN = ".%s" % KIWI_TENANTS_DOMAIN

**Comment by erikvlm** [comment]
Hmm.. not sure if that solves the issue - do you mind showing your signup/login view? I tried doing that and it just messes everything up (users get sessions in the database, but they can't actually log in/register, the pages are just being refreshed/resubmitted)
