### ISSUE TITLE
Add backend - AWS Cognito

### ISSUE THREAD

**Issue by umgelurgel** [python-social-auth/social-core#354]
https://aws.amazon.com/cognito/

**Comment by danizen** [comment]
How do I specify the app id and the secret?    I see there is a reference to setting "POOL_DOMAIN", will that be SOCIAL_AUTH_POOL_DOMAIN in my settings?

**Comment by danizen** [comment]
> How do I specify the app id and the secret? I see there is a reference to setting "POOL_DOMAIN", will that be SOCIAL_AUTH_POOL_DOMAIN in my settings?

That is a newbie question -  I am further now specifying SOCIAL_AUTH_COGNITO_POOL_DOMAIN, SOCIAL_AUTH_COGNITO_KEY, and SOCIAL_AUTH_COGNITO_SECRET.

I get farther now, but still have two questions:

- Does this backend allow me to specify the identity provider or idp_provider documented [here](https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/).

- I am getting a redirect url mismatch error - how do I tell Cognito where to redirect to?

**Comment by danizen** [comment]
> I am getting a redirect url mismatch error - how do I tell Cognito where to redirect to?

My devops team misinterpreted how the callback URI could not include a URI fragment, i.e. #whatever, and I've directed them to set the callback URI to be http;//localhost:8000/social/complete/cognito/ for now.    I still do need to understand how to provide the identity provider as a parameter.

**Comment by danizen** [comment]
I think I've answered all of my questions, thanks.

**Comment by JingleCEF** [comment]
> > I am getting a redirect url mismatch error - how do I tell Cognito where to redirect to?
> 
> My devops team misinterpreted how the callback URI could not include a URI fragment, i.e. #whatever, and I've directed them to set the callback URI to be `http://localhost:8000/social/complete/cognito/` for now. I still do need to understand how to provide the identity provider as a parameter.

How did you fix the "redirect url mismatch error"? Did you explicitly set something similar to SOCIAL_AUTH_COGNITO_POOL_DOMAIN? I get the same problem. Thank you very much!
