### ISSUE TITLE
LinkedIn using v1

### ISSUE THREAD

**Issue by barreeeiroo** [python-social-auth/social-core#356]
Hello,

I'm using this library with Django, but when using the LinkedIn OAuth2 it returns the following error:
```
HTTPError at /access/s/complete/linkedin-oauth2/
410 Client Error: Gone for url: https://api.linkedin.com/v1/people/~:(first-name,id,last-name)?format=json
```

I guess it is because the call is being made to the API v1 version, instead of the v2
However, I can see in the code that it has already been updated. May I know when a new version is going to be released?

**Comment by Amrit0991** [comment]
The PyPi version seems to be behind master from Github. This worked for me:

`pip uninstall social-auth-core`
`pip install git+https://github.com/python-social-auth/social-core`

**Comment by awachat** [comment]
@omab please check this.

**Comment by tuergeist** [comment]
@awachat Please create an official release. Git head works but I don't want to test and deploy it every day

**Comment by awachat** [comment]
Hi @omab 
I can help you with the release. I will need documentation and permissions. Let me know if that works.

Thanks.

**Comment by omab** [comment]
Version `3.2.0` released to PyPi
