### ISSUE TITLE
Problem while using 'social_core.backends.google.GoogleOAuth2' on AUTHENTICATION_BACKENDS

### ISSUE THREAD

**Issue by GMNetto** [python-social-auth/social-core#37]
I am trying to include support to authentication using the google API with facebook. However, if 

AUTHENTICATION_BACKENDS = (
    'social_core.backends.amazon.AmazonOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend'
),

for example. The facebook authentication works. On the other hand, if 

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend'
)

. I get 'module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'. I am concluding that the problem is in the Google module.

**Comment by ghickman** [comment]
What version of Python are you using and do you have [defusedxml](https://pypi.python.org/pypi/defusedxml/0.5.0) installed?  I ask because this is a [known error](https://bugs.python.org/issue29050) with Python 3.6 and DefusedXML.

**Comment by omab** [comment]
This looks a lot like the `defusedxml` error, should be fixed by the lastest change in the requirements.txt file, but also a new release was done recently that I need to check and update the requirements for.
