### ISSUE TITLE
Problem with Stripe backend documentation

### ISSUE THREAD

**Issue by balmandhunter** [python-social-auth/social-core#38]
I followed the instructions on the [backend documentation page for Stripe](http://python-social-auth.readthedocs.io/en/latest/backends/stripe.html), and used this backend authentication code:

```
SOCIAL_AUTH_AUTHENTICATION_BACKENDS = (
    ...
    'social_core.backends.stripe.StripeOAuth2',
    ...
)
```

When I tried to use `<a href="{% url 'social:begin' 'stripe' %}">Stripe</a>` in a template, I got the following error:

<img width="918" alt="screen shot 2017-02-14 at 5 13 20 pm" src="https://cloud.githubusercontent.com/assets/11546476/22956787/e8fb4f7c-f2d8-11e6-8f54-1865d6615173.png">

Replacing with `SOCIAL_AUTH_AUTHENTICATION_BACKENDS ` with `AUTHENTICATION_BACKENDS ` fixed the problem, and my link succesfuly routed me to the Stripe OAuth Login page.

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-docs/issues/9
