### ISSUE TITLE
Add Discourse SSO backend

### ISSUE THREAD

**Issue by modulitos** [python-social-auth/social-core#383]
Would it be useful to add a Discourse backend?

I already have an implementation working, and I think I can abstract it into this library with minimal effort.

One wrinkle, however, is that there is no centralized Discourse instance. So users will be required to configure the host name of their Discourse instance.

---

Here are some useful links that I discovered while implementing my Discourse SSO backend:
 * Discourse SSO docs: https://meta.discourse.org/t/using-discourse-as-a-sso-provider/32974
 * example implementation using PSA Social Core library: https://meta.discourse.org/t/discourse-doesnt-redirect-to-return-sso-url-after-user-logs-in-on-private-site/97201

**Comment by btx** [comment]
Hello, I would need this. How could I help? :)
