### ISSUE TITLE
Twitch API v3 shutdown

### ISSUE THREAD

**Issue by fedosov** [python-social-auth/social-core#386]
Twitch API v3 shutdown scheduled for September 12, 2019 according to https://dev.twitch.tv/docs/v5/guides/migration/

Authentication domain moved from https://api.twitch.tv/kraken to https://id.twitch.tv

As far as I can see that's all the changes which are related to authentication process.

**Comment by DorkmasterFlek** [comment]
Thank you!  When will a new version of this library be released next?  The old Twitch API has officially shut down now and the Twitch OAuth does not work with the most recent released version 3.2.0 from back in May.

**Comment by fedosov** [comment]
@omab any chance it can be released to PyPI? Thanks.
