### ISSUE TITLE
New Backend? Microsoft Graph

### ISSUE THREAD

**Issue by NBajanca** [python-social-auth/social-core#4]
Microsoft Graph [documentation](https://graph.microsoft.io/en-us/docs/authorization/auth_overview) says that AzureAD endpoints are used, and so it would make sense to use AzureAD Oauth2 backend.

My biggest doubt is in `SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE` where I though the correct value would be `https://graph.microsoft.com/v1.0/me`
Unfortunately, I always get this error: 

> The application named https://graph.microsoft.com/v1.0/me was not found in the tenant named ****. 

I think this is related to the fact that graph is not considered a resource by Azure AD but the documentation is a little scarce.

For my needs, I configured a new backend:
   
        def user_data(self, access_token, *args, **kwargs):
            """Grab user profile information from microsoft."""
            response = self.get_json('https://graph.microsoft.com/v1.0/me',
                                 headers={'Authorization': 'Bearer ' + access_token})
            return response   

I would like assistance to understand if I should fork my developments or if I'm doing something wrong about AzureAD backend.

**Comment by NBajanca** [comment]
After a better understanding it is possible to use the SOCIAL_AUTH_AZUREAD with Microsoft Graph by doing:

SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE = 'https://graph.microsoft.com/'

**Comment by omab** [comment]
@NBajanca I've added it to the AzureAD backend docs https://github.com/python-social-auth/social-docs/commit/499fbaaa17a85f96d7f9d9ca56de5369e3de4df3.

**Comment by NBajanca** [comment]
Thank you for this and for this great library @omab. Happy new year!

**Comment by jpatel3** [comment]
I think it needs to be updated. I am getting following error when AzureADOAuth2 backend - 

```
Sorry, but we’re having trouble signing you in.
We received a bad request.

Additional technical information:
Correlation ID: e6592900-fab7-4d10-8920-cdd63ec483ff
Timestamp: 2018-01-04 19:59:18Z
AADSTS50020: **We are unable to issue tokens from this api version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.**
```
