### ISSUE TITLE
Add backend - Mailru

### ISSUE THREAD

**Issue by pulysak** [python-social-auth/social-core#403]
There is already backend for mailru: 
https://python-social-auth.readthedocs.io/en/latest/backends/mailru.html 
https://github.com/python-social-auth/social-core/blob/master/social_core/backends/mailru.py
 - which basically use https://my.mail.ru/ - old social network for authentication.

I think it is a good idea to do a new backend for the new mail.ru Oauth - https://oauth.mail.ru/docs

**Comment by pulysak** [comment]
https://github.com/python-social-auth/social-core/pull/404

**Comment by omab** [comment]
Fixed by #404
