### ISSUE TITLE
OpenId Connect fails when no 'alg' in JWKS

### ISSUE THREAD

**Issue by kimmoahola** [python-social-auth/social-core#415]
OpenIdConnectAuth fails when JWKS does not specify the 'alg'. This line causes the exception: https://github.com/python-social-auth/social-core/blob/c8d172e3fe5129fe9c7814157684c2d83d7809e9/social_core/backends/open_id_connect.py#L165

At least Ping Identity's OpenId Connect implementation does not have the 'alg' in their JWKS URL: https://sso.connect.pingidentity.com/sso/as/jwks

According to https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation (point 7) the key defaults to RS256 if missing.

As a workaround I did something like this and it seems to work. I override OpenIdConnectAuth's get_remote_jwks_keys():

    def get_remote_jwks_keys(self):
        keys = super(MyOpenIdConnectAuth, self).get_remote_jwks_keys()
        for key in keys:
            if 'alg' not in key:
                key['alg'] = 'RS256'

        return keys

Is this a bug or am I missing something here?

**Comment by kimmoahola** [comment]
This is still relevant.

**Comment by dylantack** [comment]
I think this is addressed by https://github.com/python-social-auth/social-core/pull/661
