### ISSUE TITLE
Instagram closed new app registration. Provider should be refactored or should be deleted

### ISSUE THREAD

**Issue by yurabysaha** [python-social-auth/social-core#419]
According to the Instagram announcement:

> UPDATE: Starting October 15, 2019, new client registration and permission review on Instagram API platform are discontinued in favor of the Instagram Basic Display API. 

Need to refactor instagram backend provider, because now its not a working. 

instagram backend provider use `https://api.instagram.com/v1/users/self` for get user data, but now it should be `https://graph.instagram.com/me`. [link to the doc](https://developers.facebook.com/docs/instagram-basic-display-api/reference/me)

 Also need refactor `get_user_details` and `get_user_id` methods because response is also changed now.

But on [Instagram basic display api page](https://developers.facebook.com/docs/instagram-basic-display-api/)  we can see announcement in Limitations block.
> Instagram Basic Display is not an authentication solution. Data returned by the API cannot be used to authenticate your app users or log them into your app. If you need an authentication solution we recommend using Facebook Login instead

So maybe should just remove this provider from backend.

**Comment by KimVuu** [comment]
Is there a countermeasure for this?

**Comment by EralpB** [comment]
any news about this? how are you people solving this?

**Comment by yurabysaha** [comment]
Just remove instagram social and use facebook

**Comment by Nadjedu** [comment]
Is there a workaround or a fix planned?
