### ISSUE TITLE
race condition on access_token_expired()

### ISSUE THREAD

**Issue by NBajanca** [python-social-auth/social-core#42]
[access_token_expired](https://github.com/python-social-auth/social-core/blob/9fb7a06a0618aa88d62b980392f77b5a5f91f98f/social_core/storage.py#L94) has the following logic:

    def access_token_expired(self):
        expiration = self.expiration_timedelta()
        return expiration and expiration.total_seconds() <= 0

Why not: 

    class UserMixin(object):
        ...
        RACE_CONDITION_TIMEOUT = 2
        ...
        def access_token_expired(self):
            expiration = self.expiration_timedelta()
            return expiration and expiration.total_seconds() <= RACE_CONDITION_TIMEOUT

The strategies could override this value (thinking, for example, in creating a settings option for Django)

**Comment by omab** [comment]
What does this solve?

**Comment by NBajanca** [comment]
If the access token expires in one or two seconds it will not be treated as expired.  when used for an api service the response will be of invalid token because meanwhile it has expired.

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/3452198320bf030cb75e4582ada79fa2308408e7
