### ISSUE TITLE
Feature request: allow remapping of psa's user fields to the program's user fields

### ISSUE THREAD

**Issue by hmpf** [python-social-auth/social-core#421]
When using a custom user object, the field names that psa looks up might not match the field names on the user object. Also, there might be extra data provided by the backend that is relevant to store directly in the user object.

It'd be handy to have an agreed upon way of mapping the fields in the easiest imaginable case, when a single field from psa maps to a single but differently named field on the user object. Also, it would be good to have documentation for where more complicated rewrites and mappings could be done.

**Comment by omab** [comment]
Fixed by #422
