### ISSUE TITLE
social-auth-core >= 3.3.0 requires Unidecode, which is GPLv2

### ISSUE THREAD

**Issue by ryanpetrello** [python-social-auth/social-core#449]
see: https://github.com/python-social-auth/social-core/pull/388

@tinhien11 @omab are you all aware that Unidecode is GPLv2? This new requirement will likely affect how/whether downstream open source projects are able to consume social-auth-core.

It also seems problematic in general, given social-auth's BSD licensing.

related: ansible/awx#6410

**Comment by omab** [comment]
Thanks @ryanpetrello, I didn't note this license incompatibility in my review process, I'll look into removing the dependency.

**Comment by ryanpetrello** [comment]
Thank you @omab 😄!

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/5a2cac02394cc3fd93e705af373043b896eaa5e8 and released in version `3.3.1`.
