### ISSUE TITLE
Microsoft provider

### ISSUE THREAD

**Issue by TAnas0** [python-social-auth/social-core#451]
Hello,

I have successfully used social-django-auth to quickly implement Gogle authentication, but I am facing an issue with the Microsoft provider, which I believe originates here in this repository.

For additional cotnext, I am using Django and using this package through [social-app-django](https://github.com/python-social-auth/social-app-django)

### Expected behaviour

Conclude the Microsoft Graph authentication by getting the token back from Microsoft.

### Actual behaviour

I get a 400 response from the URL of the Microsoft tenant while trying to get the token:
```
HTTPError at /oauth/complete/microsoft-graph/

400 Client Error: Bad Request for url: https://login.microsoftonline.com/common/oauth2/v2.0/token
```

### Any other comments?
I am using the `microsoft-graph` provider in the file `social_core/backends/microsoft.py`. Is this the recommended way of implementing? Or I should be doing [this](https://github.com/python-social-auth/social-core/issues/113#issuecomment-317178405)?

I can see that the `microsoft.py` file was last updated 3 years ago. Is it up-to-date with Microsoft's API?
If someone could review this and provide me with more information, maybe I could pull a PR together if Microsoft login is not working

If someone could review this and provide me with more information, maybe I could pull a PR together if Microsoft login is not working

**Comment by JJZolper** [comment]
Yeah I get the same 400 error. Wondering the same thing if it's been tested with the most recent Graph API, etc.

@nijel or @omab are you able to help us / verify what is supported?

**Comment by JJZolper** [comment]
I think this may need a rewrite using MSAL instead: https://github.com/AzureAD/microsoft-authentication-library-for-python

Thoughts?
