### ISSUE TITLE
https://oauth.net/code/python/ link is 404

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-social-auth/social-core#457]
the link on https://oauth.net/code/python/ to social auth is 404.

it links to https://python-social-auth-docs.readthedocs.io/en/latest/ .

**Comment by ThomasWaldmann** [comment]
If noone fixed it, there is no reason to close it.

**Comment by ThomasWaldmann** [comment]
Who thought that a stale bot is a good idea? It just annoys people who report issues.

**Comment by ThomasWaldmann** [comment]
If noone fixed it, there is no reason to close it.

**Comment by ThomasWaldmann** [comment]
not fixed.

**Comment by omab** [comment]
The page at oauth.net is not controlled by this project. I've created a PR on their project with the change https://github.com/aaronpk/oauth.net/pull/250
