### ISSUE TITLE
okta backend should return email for email instead of preferred_username

### ISSUE THREAD

**Issue by sdementen** [python-social-auth/social-core#458]
### Expected behaviour

With the OktaOAuth2 backend, I expect the email of the user to be taken from the email claim of the JWT.

### Actual behaviour

The OktaOAuth2 backend returns for the django user email the preferred_username instead of the email.

### What are the steps to reproduce this issue?

Configure social django with 
```
AUTHENTICATION_BACKENDS = [
    "social_core.backends.okta.OktaOAuth2",
]
```
and use it ...

### Any logs, error output, etc?

The line https://github.com/python-social-auth/social-core/blob/master/social_core/backends/okta.py#L54 shows the issue.
It should be replaced by
```
                'email': response.get('email') or '',
```
The DEFAULT_SCOPE should also be updated to:
```
    DEFAULT_SCOPE = ["openid", "profile", "email"]
```

**Comment by selten** [comment]
@sdementen I think PR #461 has fixed this so this issue can probably be closed.

**Comment by sdementen** [comment]
Yes indeed, tx!
