### ISSUE TITLE
Unable to login as an Azure AD Guest User

### ISSUE THREAD

**Issue by sthomae01** [python-social-auth/social-core#467]
We are using a translation tool (Weblate) in our company and would like to have guest users of our Active Directory to sign in too.

### Expected behaviour

A guest user simply signs in and it is just like signing in as a normal user.

### Actual behaviour

An error occurs when trying this which says: "No E-mail-address received by a third-party athentication service. Please register by E-mail instead"
We were redirected here by a Weblate-programmer.

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Having a guest account in Azure AD
2. Signing in with social-core
3. Error occurs

### Any logs, error output, etc?

/

### Any other comments?

/

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-core/pull/594 might address this, can you test that?
