### ISSUE TITLE
Auth0 backend improvements

### ISSUE THREAD

**Issue by lbalmaceda** [python-social-auth/social-core#468]
Hi team 👋 
In our login page at **Auth0**, we accept certain query parameters that can change how the form is being shown to the user. In this particular case, I wanted to add the `screen_hint` parameter which would tell the form to show displaying the "Sign Up" screen/tab first. This parameter should be dynamically added only for the sign-up scenario. The log-in scenario should remain the same, without the parameter or a different value. You'd be surprised by the number of people that want a sign-up button that takes them to the "Sign Up" screen and not the "Log In" one.

In order to do that with python-social-auth, I explored the following options:
* Hardcoding the query in the [authorization URL](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/auth0.py#L25) - Would affect all requests 🚫 
* Adding the extra parameters in the `SOCIAL_AUTH_{backend}_EXTRA_ARGUMENTS` setting - Would affect all requests 🚫 
* Creating a new entry in the `urls.py` mapping file to call my own function when `/signup` is called - I was not able to access the strategy's "final" generated authorization_url to add the parameter there ⚠️  I think it could have worked if I whitelisted the parameter and redirected to the login page (see below).
* Overriding the `auth_extra_arguments` function in the backend to check if the parameters were present in the "local login" request and adding them to the _super_ ones. First, whitelisting these in `SOCIAL_AUTH_FIELDS_STORED_IN_SESSION` - I'm hardcoding the query in the template file. This worked fine  ✔️ 

There are a few things I wanted to ask.
1. Is there a better, simpler way to achieve what I did above?
2. Auth0 [implements OIDC](https://auth0.com/docs/protocols), would you accept a PR that creates a new backend that extends this class?
3. Adding extra parameters to the authorization_url dynamically as the case explained above should be straightforward. Unless there's a simpler solution (1), I was thinking the backend could do this whitelisting and addition of common parameters (either common to the protocol or the backend) to the authorization_url internally if they were present in the "local login" request. Something like what I did to resolve this use case. Would you accept a PR that overrides the `auth_extra_arguments` for the auth0 backend (or the OIDC variant, if introduced) and checks for presence before adding the query values?

**Comment by lbalmaceda** [comment]
Bump

**Comment by JensAstrup** [comment]
For everyone else's benefit, I also thought the `EXTRA_ARGUMENTS` setting would set the values on every request, but thanks to #163 I realized the following is possible (and I am now using it for the same issue you have with Auth0):

```
SOCIAL_AUTH_AUTH0_AUTH_EXTRA_ARGUMENTS = {
    'initialScreen': '',
}
```

Then you can do this: `reverse('social:begin', kwargs=dict(backend='auth0')) + '?initialScreen=signUp'`

**Comment by lbalmaceda** [comment]
Bump
