### ISSUE TITLE
Sign in with Apple:  Multiple scopes separated by space encoded as plus (+) instead of %20

### ISSUE THREAD

**Issue by dcmoore-gd** [python-social-auth/social-core#470]
### Expected behaviour

Multiple scopes separated in query string parameter by a space encoded as `%20`.

### Actual behaviour

Multiple scopes separated in query string parameter by a space encoded as `+`.

### Any other comments?

Apple is expecting it to be space separated but the spaces encoded as `%20` as mentioned in [their documentation](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332113):
> Use space separation and percent-encoding for multiple scopes; for example, "scope=name%20email".

**Comment by mbaechtold** [comment]
I can second this. Here's a workaround until the bug is being fixed:

```
settings.SOCIAL_AUTH_APPLE_ID_SCOPE = ["name%20email"]
```

**Comment by dcmoore-gd** [comment]
Aww stalebot, there's still a PR open for this!  https://github.com/python-social-auth/social-core/pull/493
