### ISSUE TITLE
[Apple Sign-in] Support for multiple client IDs

### ISSUE THREAD

**Issue by AlvinTCH** [python-social-auth/social-core#477]
### Expected behaviour

Apple Sign-in for JS requires Service ID (where we put the redirect URL) as the client ID. Expected the same ID could be used for app development

### Actual behaviour

I kind of expected the same ID to be used in building an iOS app as client ID. But when using the same service ID as the client ID, the authorization did not pass. I had to use the bundle ID for the application. As the backend could only support 1 client-id, I had to choose between web or app implementation of the apple sign-in (which of course I chose the app implementation)

### What are the steps to reproduce this issue?

1. Develop apple sign-in in app
2. Use service ID for backend
3. "Authorization got cancelled"

Fixed when I changed the client-id to use the bundle ID

### Any other comments?

Is it possible to support multiple client-ids in a list and search for the appropriate client-id using the "aud" value when decoding the id_token?

**Comment by AlvinTCH** [comment]
Sorry I just tested and actually the array parameter is supported

**Comment by rj76** [comment]
@AlvinTCH Could you please share how you fixed this?

**Comment by AlvinTCH** [comment]
@rj76 I can't exactly remember what I did to resolve this issue but possibly for my app that is written using Django, I put the "SOCIAL_AUTH_APPLE_ID_CLIENT" parameter as an array of client IDs rather than a string and it works. Hope that helps
