### ISSUE TITLE
How create django users without first_name and last_name

### ISSUE THREAD

**Issue by icruces** [python-social-auth/social-core#48]
I have configured the library to only fetch **email** and **username** from Facebook backend using the settings property `SOCIAL_AUTH_USER_FIELDS`.
However, the user is always created with the **first_name** and **last_name** fields populated. 

I have also tried with the `SOCIAL_AUTH_FACEBOOK_SCOPE `and `PROTECTED_USER_FIELDS` but those fields always get populated.

I have being debugging and I see that the fields are not fetched from Facebook but they are generated anyways from the **fullname**.

Is there anyway to avoid set those fields in the user object?

**Comment by omab** [comment]
Override the corresponding pipeline function with one with the desired behavior.

**Comment by icruces** [comment]
Thanks, I will do that.
