### ISSUE TITLE
Sign in with apple: Unable to store the user's name

### ISSUE THREAD

**Issue by mbaechtold** [python-social-auth/social-core#482]
Apple sends back the user data under the key `user` but `social-core` expects a key `name` in the response:

https://github.com/python-social-auth/social-core/blob/9d93069564a60495e0ebd697b33e16fcff14195b/social_core/backends/apple.py#L135-L141

Apple has documented this at https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332115

> **user**
> A JSON string containing the data requested in the scope property.
> The returned data is in the following format:
> { "name": { "firstName": string, "lastName": string }, "email": string }

So in case anybody wants to fetch the user's name, the following enhancement to the backend would do the trick:

```
class ImprovedAppleIdAuth(AppleIdAuth):
    SCOPE_SEPARATOR = "%20"  # A workaround for https://github.com/python-social-auth/social-core/issues/470

    def get_user_details(self, response):
        """
        Apple sends back the user data under the key `user`, see
        https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332115

        From the docs:
            A JSON string containing the data requested in the scope property.
            The returned data is in the following format:
            { "name": { "firstName": string, "lastName": string }, "email": string }
        """
        user_data = json.loads(self.data.get("user", "{}"))

        # The email is already present in the response, so we remove it.
        user_data.pop("email", None)

        response["name"] = user_data
        return super().get_user_details(response)

    def extra_data(self, user, uid, response, details=None, *args, **kwargs):
        data = super().extra_data(user, uid, response, details, *args, **kwargs)
        data["email_verified"] = response.get("email_verified")
        data["is_private_email"] = response.get("is_private_email")
        return data
```

Oh and by the way: the data is only sent upon the very first authorisation of your app, see https://developer.apple.com/forums/thread/121496?answerId=379297022#379297022 🤔 So make sure to remove the app authorisation at https://appleid.apple.com/account/manage when debugging your app.

**Comment by alexislg2** [comment]
Thank you @mbaechtold . Your improvement looks great. Unfortunately, it does not work for me.
I am using your ImprovedAppleIdAuth, but I still cannot get the name.
I deleted the app authorisation in my apple account

But when I print `self.data`, the value is always `<QueryDict: {}>`

What am I doing wrong?

**Comment by alexislg2** [comment]
answering to myself:

I think the reason why I don't get firstname and lastname is because Apple transmits them only once and I am using the auth on the client side (using the app or apple.js). Therefore these infos are only sent to the client and cannot be retrieved by the backend.

**Comment by mbaechtold** [comment]
@alexislg2, that's what I meant with the very last sentence in the description of this issue:

> Oh and by the way: the data is only sent upon the very first authorisation of your app, see https://developer.apple.com/forums/thread/121496?answerId=379297022#379297022 🤔 So make sure to remove the app authorisation at https://appleid.apple.com/account/manage when debugging your app.
