### ISSUE TITLE
Sign In with Apple requires SameSite=None session cookie

### ISSUE THREAD

**Issue by jarshwah** [python-social-auth/social-core#492]
### Expected behaviour

I can sign in with apple where the session cookie is configured `SESSION_COOKIE_SAMESITE = "Lax"`

### Actual behaviour

```
AuthStateMissing at /account/social/complete/apple-id/
Session value state missing.
```

### What are the steps to reproduce this issue?

1. Django is configured with `SESSION_COOKIE_SAMESITE = "Lax"`.
2. Enable apple id sign is as per documentation.
3. Sign in
4. On the redirect, get a 500 error

### Any other comments?

This happens because apple have decided to implement their redirect with a POST rather than a GET as per https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms

The consequences of this is that a default of "Lax" for your session cookie does not work. Changing it to None will appear to work - for some browsers. But for Chrome treats a missing SameSite attribute as Lax. Setting it to the string "none" will be interpreted as strict by a bunch of browsers.

### Potential Fix

I don't know that there is much to be done from the PSA side of things - this issue is more a warning to future devs. PSA should consider alternative methods for verifying the state without using the session cookie. I have no real ideas on how that can be done safely.

An idea might be to intercept all POST requests to the Complete handler, encode the data in some way, and redirect using GET and attaching the data as URL parameters? The redirect from POST to GET will allow the cookie to be used, but it might also cause the session cookie to be recreated which would defeat the purpose anyway.

I've anger tweeted at twitter support to consider using GET for the redirect, but I have very little confidence that will get in front of anyone making decisions.

**Comment by RudaF** [comment]
Hey @jarshwah have you reached a solution? I've been dealing with the same problem and had a similar idea of using a redirect from POST to GET, but haven't had any success yet.

**Comment by jarshwah** [comment]
Sorry but I don't remember how we solved for this problem and I don't work at that company anymore. You might find some of the discussion in the twitter thread I started: https://twitter.com/jarshwah/status/1283748901166538757?s=20&t=pUq_zbPH8mDXdoQO1CqsAQ

**Comment by RudaF** [comment]
Thank you @jarshwah 

I've actualy reached a solution by overwriting the social-auth view url and, when the request is a POST, I return a redirect to the same url, turning it into a GET request.

`# urls.py
urlpatterns = [
    ...
    path('complete/apple-id/', views_auth.apple_social_auth, name='complete'),
    ...
]

# views.py
from social_django.urls import views as social_auth_views

@csrf_exempt
def apple_social_auth(request):
    if request.method == 'POST':
        redirect_url = f'{request.path}?{request.body.decode("utf-8")}'
        return redirect(redirect_url)
    return social_auth_views.complete(request, 'apple-id')
`

**Comment by pmaccamp** [comment]
Thanks @RudaF saved me a lot of time :)
