### ISSUE TITLE
Partial pipeline step stores plain passwords in the database

### ISSUE THREAD

**Issue by GergelyKalmar** [python-social-auth/social-core#494]
### Expected behaviour

When using a partial pipeline step sensitive data does not get stored in the database.

### Actual behaviour

Raw plain passwords are stored in the database while a partial pipeline is waiting to be resumed. In particular, this is what I can see in the ``data`` field of the ``social_auth_partial`` table:

```
{
    "args": [],
    "kwargs": {
        ...
        "response": {
            "email": [
                "test@example.com"
            ],
            "first_name": [
                "Test"
            ],
            "last_name": [
                "User"
            ],
            "password": [
                "123"
            ]
        },
        ...
    }
}
```

Only partly related, but the [documentation](https://python-social-auth.readthedocs.io/en/latest/developer_intro.html#interrupting-the-pipeline-and-communicating-with-views) shows an example for collecting passwords in pipelines using partial pipeline steps which _also_ ends up storing plain passwords in the session storage (usually the database). In particular, instead of doing this:

```
request.session['local_password'] = form.cleaned_data['secret_word']  # PLEASE DON'T DO THIS
```

one should definitely do

```
from django.contrib.auth.hashers import make_password
...
request.session['password_hash'] = make_password(form.cleaned_data['secret_word'])
```

and then in the partial pipeline

```
password_hash = strategy.session_get('password_hash', None)
...
user.password = password_hash
user.save(update_fields=['password'])
```

instead.

### What are the steps to reproduce this issue?

1. Enable the ``social_core.pipeline.mail.mail_validation`` partial pipeline or use any other partial pipeline
2. Use the email or username auth backend
3. Submit a form with the user email (or username) and password to begin the social auth process but do not validate the user email yet
4. Inspect the ``data`` field in the ``social_auth_partial`` table

Although the data is deleted once the validation is complete, there are circumstances where plain passwords may be accessible for a long period of time (e.g. if a backup is created in this time frame or if the user does not complete the validation for a while).

### Any other comments?

In my case I want to achieve the following user flow for account creation: gather email & password > validate email > create user > set user password. I can use the session storage to pass the hashed password from before the email validation to after, therefore excluding this field from being stored in the partial pipeline ``response`` object would solve the problem for me. Is this possible somehow? In general, I think that the ``response`` object should only store data by default that is absolutely needed for the default pipeline steps to succeed.

**Comment by GergelyKalmar** [comment]
As a workaround for now I've introduced an additional pipeline step that simply hashes the password before it reaches the partial pipeline:

```
from django.contrib.auth.hashers import make_password

def hash_password(strategy, response, *args, **kwargs):
    password = strategy.request_data().get('password')
    response['password'] = make_password(password)
    return {'response': response}
```

Nevertheless, keeping this info out by default would be much nicer I think.

**Comment by GregoryAveryWeir** [comment]
This is a huge issue with the doc examples that probably shouldn't be closed as stale.
