### ISSUE TITLE
Can not get name with apple sign in

### ISSUE THREAD

**Issue by p02diada** [python-social-auth/social-core#501]
### Expected behaviour

I can not get name with apple sign in.

### What are the steps to reproduce this issue?

Scope:

SOCIAL_AUTH_APPLE_ID_SCOPE = ['email', 'name']

**Comment by mbaechtold** [comment]
This might be a duplicate of https://github.com/python-social-auth/social-core/issues/482

**Comment by timabbott** [comment]
Please don't close this issue, it is important and unresolved.

-Tim Abbott (mobile)

**Comment by nijel** [comment]
Maybe related to https://github.com/python-social-auth/social-core/pull/490
