### ISSUE TITLE
Fix Yahoo oauth2

### ISSUE THREAD

**Issue by catharine31** [python-social-auth/social-core#518]
Yahoo has stopped supporting Yahoo OpenID Connect, instead of using yahoo-oauth2. However, there are some errors in Yahoo’s document which results in login failure. Therefore, our pull request #512 has modified this problem. After testing, login function works successfully now. Because of some issues in Travis CI test case, some testing failure may still occur. However, we do not modify google backend and the test case. The testing failure can not be attributed to our modification in yahoo. In sum, please kindly review and accept our pull request(#512). Thanks.

**Comment by dstndstn** [comment]
Thank you for this fix!  I tested it for my site and it is working correctly!
