### ISSUE TITLE
 Instagram Legacy API was deprecated

### ISSUE THREAD

**Issue by hadrizi** [python-social-auth/social-core#527]
Instagram Legacy API was deprecated on June 29.

See:
https://www.instagram.com/developer/

Using authentication via Instagram is not possible because of this problem.

**Comment by Edmond7450** [comment]
You can use Instagram Basic Display API.
https://developers.facebook.com/docs/instagram-basic-display-api

For it, I fixed /social/backends/instagram.py
I just added REDIRECT_STATE = False in the 13th line.
Hope this helps.
