### ISSUE TITLE
Logout user before starting mail_validation pipeline (Important)

### ISSUE THREAD

**Issue by a1Gupta** [python-social-auth/social-core#54]
Assume there are two users - User A and User B.

User A is logged in the browser.
Now User B, opens his email and clicks on the email confirmation link in the same browser. So, on confirmation the social backend of User B will get connected to User A's account.

**Solution**
Logout user before email confirmation in `mail_validation` pipeline.

@omab Check this, seems like a security issue.

**Comment by omab** [comment]
That happens because that's how the `complete` route works since it's used to associate several social accounts to a single user.

The example is setup for simplicity but on real projects it should link to a URL that takes care of the logging out of users or any other security check required by the project.

**Comment by a1Gupta** [comment]
I just noticed this. Logging out user in pipeline if `verification_code` param exists will be helpful to everyone if possible.

```
        if 'verification_code' in data:
           # code to logout user
            backend.strategy.session_pop('email_validation_address')
            if (not backend.strategy.validate_email(
                    details['email'], data['verification_code'])):
                raise InvalidEmail(backend)
```
Can this be done or using a different url is better option?

**Comment by virtosubogdan** [comment]
Maybe it would be a good idea to explicitly specify this behavior in the docs.
It could also be and option in the settings if you want to associate accounts or redirect to a page.

It is a major problem if you only realize this behavior after you already started to use social-core.
