### ISSUE TITLE
[Question] ADAL deprecation in favor of MSAL

### ISSUE THREAD

**Issue by lucasvazq** [python-social-auth/social-core#545]
Hi! Good day.

I am a Django developer, and in my work there is a problem that I have to solve regarding the [Depreciation of Active Directory Authentication Library in favor of Microsoft Authentication Library][deprecation].

Basically, now we have to use Microsoft Graph instead of Azure AD Graph and MSAL instead of ADAL.

I would like to know if this implies any changes related to this library or with the [social-app-django] library.

Some info: on the website I work for, we are using the `azuread.AzureADOAuth2` backend.

Thanks!

[social-app-django]: https://github.com/python-social-auth/social-app-django
[deprecation]: https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

**Comment by omab** [comment]
If I understand Microsoft notice, that change will deprecated the auth implementations that use AzureAD currently implemented on this lib, but looks like the new auth API is already implemented with the auth backend at https://github.com/python-social-auth/social-core/blob/master/social_core/backends/microsoft.py. There's still a migration process for sure, it depends on the compatibility between these two, maybe the user unique identifier is the same, so matching accounts can be easily acomplished.

I'd suggest starting a dev environment with a clean DB and support both auth methods, logging with one and then the other and try to find what could be useful to migrate associations from the deprecated backend to the new one. A custom pipeline fiction could be handy on easing up this migration.

**Comment by lucasvazq** [comment]
I want to show the results I got after doing some tests.

The tests are done based on changes in the API permissions and consents for Microsoft Graph and Azure AD Graph

Related link: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis

The permissions and consents that I refer for both Azure AD Graph and Microsof Graph include:
- Delegated
  - Directory.Read.All
  - User.Read
  - User.Read.All
  - User.Read.Basic.All
- Application
  - Directory.Read.All

<table>
<tbody>
  <tr>
    <td>Azure AD Graph permissions</td>
    <td>Yes</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Azure AD Graph admin consent</td>
    <td>-</td>
    <td>Yes</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Microsoft Graph permissions</td>
    <td>-</td>
    <td>-</td>
    <td>Yes</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Microsoft Graph admin consent</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>Yes</td>
  </tr>
  <tr>
    <td colspan="5">Results</td>
  </tr>
  <tr>
    <td>AzureADOAuth2 backend</td>
    <td>AADSTS650056 Error</td>
    <td>Success</td>
    <td>Need admin approval Error</td>
    <td>Success</td>
  </tr>
  <tr>
    <td>MicrosoftOAuth2 backend</td>
    <td>Success</td>
    <td>Success</td>
    <td>Success</td>
    <td>Success</td>
  </tr>
</tbody>
</table>

AzureADOAuth2 backend includes in the settings (django) the following constant:
```
SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE = 'https://graph.microsoft.com/'
```

One of the differences that I noticed, is that in pipelines, the UID argument differs between the backends.
The one in AzureADOAuth2 is the `upn` value fetched from the response.
The one in MicrosoftOAuth2 is the `id` value fetched from the response.
This can cause problems if we have a custom pipeline and use the UID as the User Principal Name.
