### ISSUE TITLE
Line oauth should not identify 'statusMessage' as error when getting user data

### ISSUE THREAD

**Issue by iamgeorgelee** [python-social-auth/social-core#55]
https://github.com/python-social-auth/social-core/blob/master/social_core/backends/line.py#L39

I actually get a success response when calling `user_data` like below, but being processed as error because it contains `statusMessage`:

> {u'displayName': u'George Lee',
> u'mid': u'XXXXX',
> u'pictureUrl': XXXXX',
> u'statusMessage': u'My status'}`

**Comment by iamgeorgelee** [comment]
I'll create a PR for the fix later

**Comment by beoreoji** [comment]
Why is it closed? 
This has not been solved yet.
