### ISSUE TITLE
[Question/Issue] Issue with ORCID Sign In - do_auth

### ISSUE THREAD

**Issue by asencis** [python-social-auth/social-core#552]
I've recently been trying to integrate social authentication into my application - however, I am seeing a bit of a stumbling block when it comes to the `self.do_auth` call:

```
data = self.user_data(access_token, *args, **kwargs)
```

Which in turn, calls the `user_data` call within the orcid backend. (social_core.backends.orcid).

However, this seems to be failing:

```
kwargs['response']['orcid'])
KeyError: 'response'
```

So the response object isn't being passed into the keyword arguments...

**_Would anyone know possibly why this could happen?_**

I'm using `python-social-auth-core` with the following packages:

```
Django==3.1.1
django-oauth-toolkit==1.3.2
djangorestframework==3.12.0
social-auth-core==3.3.3
social-auth-app-django==4.0.0
drf-social-oauth2==1.0.8
```

### Any logs, error output, etc?

The traceback for this particular error is:

```
web_1          |   File "/usr/local/lib/python3.8/site-packages/drf_social_oauth2/oauth2_endpoints.py", line 91, in create_token_response
web_1          |     return grant_type_handler.create_token_response(
web_1          |   File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 60, in create_token_response
web_1          |     self.validate_token_request(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/drf_social_oauth2/oauth2_grants.py", line 100, in validate_token_request
web_1          |     user = backend.do_auth(access_token=request.token)
web_1          |   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 251, in wrapper
web_1          |     return func(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 410, in do_auth
web_1          |     data = self.user_data(access_token, *args, **kwargs)
web_1          |   File "/usr/src/app/api/authentication/backends/orcid.py", line 66, in user_data
web_1          |     kwargs['response']['orcid']),
web_1          | KeyError: 'response'
```

### Any other comments?

If there's anything else you need from me, please let me know and I will provide the relevant details if needed.

**Comment by omab** [comment]
Looks like you are integrating with `drf-social-oauth2` which issues this call [backend.do_auth(access_token=request.token)](https://github.com/wagnerdelima/drf-social-oauth2/blob/872efdc49aaa3e0bf235b6c66bfa2f3151ce055a/drf_social_oauth2/oauth2_grants.py#L100), that call is missing the extra parameters needed by ORCID OAuth2 backend.

Please, fill a bug on `drf-social-auth2` project.

**Comment by asencis** [comment]
@omab Will do.
