### ISSUE TITLE
[Request] Request to be added as a contributor

### ISSUE THREAD

**Issue by asencis** [python-social-auth/social-core#553]
We have an updated fix for the orcid.py backend module following the new USER_DATA_URL method outlined here:

[ORCID_AUTH_WITH_OPENID_CONNECT](https://github.com/ORCID/ORCID-Source/blob/master/orcid-web/ORCID_AUTH_WITH_OPENID_CONNECT.md#other-endpoints).

We have a hotfix ready to push up for a PR.

**Comment by nijel** [comment]
Please push the PR, we will review it and eventually merge, there is no need to become a maintainer to merge a single fix.

If you want to become maintainer anyway, see https://github.com/python-social-auth/social-core/issues/539 for desired workflow.

**Comment by asencis** [comment]
@nijel Thanks for your reply. I seem to unable to push to this repo...

**Comment by nijel** [comment]
Push to your fork and open a pull request, see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by asencis** [comment]
@nijel PR ready to review. Thank you.
