### ISSUE TITLE
Endpoint depending behaviour - create_user

### ISSUE THREAD

**Issue by BojanKogoj** [python-social-auth/social-core#56]
I would like to have two endpoints
`/auth/login`
`/auth/check_user`

The first would create user account if it doesn't exist or login if it does.
The second would return user data if he has an account in or throw an exception if he doesn't. Any way to do this?

[Authentication Pipeline](http://python-social-auth-docs.readthedocs.io/en/latest/pipeline.html#authentication-pipeline) mentions `social_core.pipeline.user.create_user`, but this doesn't look like it could be endpoint specific.

The second endpoint would be used by an external service (another platform).

**Comment by BojanKogoj** [comment]
As a temporary fix I did something like this (token goes through POST parameter)

```python
    def create(self, validated_data):

        from social_core.backends.facebook import FacebookOAuth2
        fb = FacebookOAuth2()
        token = validated_data.get('token')

        try:
            data = fb.user_data(token)
        except:
            raise exceptions.AuthenticationFailed(_('Incorrect token'))

        try:
            email = data.get('email')
            user = User.objects.get(email=email)
        except:
            raise exceptions.AuthenticationFailed(_('User has no account'))

**Comment by omab** [comment]
`social_core.pipeline.user.create_user` will create the user unless it already exists, it won't take into account your case, but you can replace it with a function that fits your needs, the `request` will be accesible at `strategy.request`.
