### ISSUE TITLE
Azure authentication access_token does not appear work. 

### ISSUE THREAD

**Issue by kagenami** [python-social-auth/social-core#561]
When trying to retrieve an access token for a user logged in using the azuread-oauth2 backend the value we are getting back for the access_token via extra_data does not seem to be a valid access token for querying the Microsoft Graph API.

What we get back when attempting to leverage the access token is a CompactToken parsing error.

Our SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE is set to https://graph.microsoft.com/.

As per the docs we have encountered everything should be working, but as I said, the access token appears to be wrong.

Any help would be appreciated.

**Comment by nijel** [comment]
Maybe related to https://github.com/python-social-auth/social-core/issues/566?

**Comment by kagenami** [comment]
I believe it may be similar to #566. I ended up creating a new backend for the auth mechanism with upgraded Azure v2 urls. We determined that that was in fact the cause of our token issues.

**Comment by nijel** [comment]
Okay, it should be fixed by https://github.com/python-social-auth/social-core/pull/567
