### ISSUE TITLE
Installation is breaking because of cryptography dependencies

### ISSUE THREAD

**Issue by nishitsjsu** [python-social-auth/social-core#562]
### Expected behaviour

Installation should be successful

### Actual behaviour

Installation in the `nginx:alpine` base image is failing because of the dependency on the cryptography package.

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Take `nginx:alpine` base image
2. install `social-auth-core` dependency using pip
3. It will fail while building the wheel for `cryptography`

### Debug logs

Debug Output

```
 =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================

  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
```

### Other Comments

Expand the issue with any details you find appropriate to solve or reproduce it.

- Docker Container
- nginx:alpine base image
- dependency on cryptography (https://github.com/pyca/cryptography/issues/3178)

In the new release `Cryptography` package has added dependencies on the Rust compiler that don't come by default in the Alpine base image. Hence the installation is failing. Try to add rust compilers first when they are not available.

**Comment by nijel** [comment]
Cryptography [ships manylinux wheels](https://pypi.org/project/cryptography/#files) to avoid need for rust compiler in many cases. The problem is that these are not compatible with alpine. Install rust compiler on the container to build the module yourself. If you would followed the links in the error message you would have figured it out: https://cryptography.io/en/latest/installation.html#alpine

I don't think we can do anything about this.
