### ISSUE TITLE
Decoding of apple token fails (AppleIDAuth.decode_id_token method)

### ISSUE THREAD

**Issue by PawelRoman** [python-social-auth/social-core#563]
### Expected behaviour

I have the following apple ID token value: 'c5014cab0e73a4db89069bd323cfd1006.0.rrvs.kR_AUio9ROCdxMFTBtA9bQ'
Token should be decoded correctly by the AppleIDAuth.decode_id_token() method .

### Actual behaviour

Error occurs. Down below in the call chain through the jwt module, the base64.py module throws the following exception:
"Invalid base64-encoded string: number of data characters (33) cannot be 1 more than a multiple of 4"

### What are the steps to reproduce this issue?

Pass 'c5014cab0e73a4db89069bd323cfd1006.0.rrvs.kR_AUio9ROCdxMFTBtA9bQ' to AppleIDAuth.decode_id_token() method

### Any other comments?

I found this while using a higher-level library drf_social_oauth2 which integrates social-core with django rest framework. The lib makes a call to decode_id_token which in turn makes a call jwt.get_unverified_header, which starts the call chain down to base64 module which fails with the above mentioned error.

I am quite sure the token is valid. It was obtained via a native apple SDK.  If you believe the token is incorrect, can you share a sample token which works correctly with AppleIDAuth.decode_id_token()  method? 

Relevant libs:

Django==3.1.2
djangorestframework==3.11.1
drf-social-oauth2==1.0.8
social-auth-core==4.0.3

**Comment by PawelRoman** [comment]
My mistake. That value is not an access token, but an authorization code. Closing.

**Comment by 1vank1n** [comment]
> My mistake. That value is not an access token, but an authorization code. Closing.

Pawel, how are you fixed it? I've get `authorization code` too.
