### ISSUE TITLE
GoogleOAuth2 backend and django permissions

### ISSUE THREAD

**Issue by thismatters** [python-social-auth/social-core#569]
### Expected behaviour

After adding a permission (e.g. `some_app.change_somemodel`) to user `someuser` via django admin and setting that user to staff status, the user--when logged in and on the admin page--should see `some_app` and `somemodel` in the index and by clicking through should be able to change an instance of `SomeModel`. Moreover, on the shell running `someuser.has_perms('some_app.change_somemodel')` should return `True`.

### Actual behaviour

After adding permissions to a user and setting them to staff status they see "You don’t have permission to view or edit anything." on the Django admin page.

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Set `AUTHENTICATION_BACKENDS` to `["social_core.backends.google.GoogleOAuth2"]`
2. Have some model
3. Create a user account
   * set that user to staff status
   * give them permission to access a model
4. Log in as that user
5. Visit the django admin
6. Observe permission warning.

### Any other comments?

It seems that the `GoogleOAuth2` backend does not implement the `has_perm` method. 

I do *not* wish to allow users to login with username/password so I have not included `'django.contrib.auth.backends.ModelBackend'` in `AUTHENTICATION_BACKENDS`, per [the PSA documentation](https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#authentication-backends).

**Comment by arnaudceol** [comment]
Hi, I have the same problem with keycloak.

**Comment by maiksprenger** [comment]
I found this issue useful to confirm my suspicion. It seems PSA does not implement `has_perm`, so permissions set on the User model are not taken into account.
