### ISSUE TITLE
Errors with AWS Cognito

### ISSUE THREAD

**Issue by tawl20q4** [python-social-auth/social-core#575]
### Actual behaviour

Errors with AWS Cognito, as oauth2 provider

### What are the steps to reproduce this issue?

1. django 2.2.19 demo app + social auth app django 4.0.0.
2. AWS Cognito oauth2 provider
3. erros, eg. id not picked up from django settings into Cognito auth url

### Any other comments?

Are these up-to-date?:

https://github.com/python-social-auth/social-core/blob/4.1.0/social_core/backends/cognito.py

https://python-social-auth.readthedocs.io/en/latest/backends/cognito.html

**Comment by maciejstromich** [comment]
Have you tried adding `"social_core.backends.cognito.CognitoOAuth2",` to `AUTHENTICATION_BACKENDS` instead of `SOCIAL_AUTH_AUTHENTICATION_BACKENDS`.  Except this difference between mentioned docs and our local implementation there's nothing else and it works on our side.
