### ISSUE TITLE
auth_time on refresh token

### ISSUE THREAD

**Issue by NBajanca** [python-social-auth/social-core#58]
When ``refresh_token()`` from ``storage.py`` is called the value of ``auth_time`` is not updated (the value of the ``access_token`` and so on is updated).

My code:

    self.social = user.social_auth.get(provider='custom')
    if self.social.access_token_expired():
        strategy = load_strategy()
        self.social.refresh_token(strategy)

The value of the ``access_token`` is updated but not the ``auth_time``.

My solution was adding two lines:

    self.social.extra_data['auth_time'] = int(time.time())
    self.social.save()

But there must be a better solution because every time the token is refreshed this is assumed.

**Comment by NBajanca** [comment]
This affects my PR #41

**Comment by omab** [comment]
I need to rework the `auth_time` storage, currently doing it in `extra_data` is not correct.
