### ISSUE TITLE
500 error for Keycloak oauth2 login - AuthFailed:

### ISSUE THREAD

**Issue by atodorov** [python-social-auth/social-core#599]
### Expected behaviour

Authentication suceeds.

### Actual behaviour

500 error with traceback:

```
AuthFailed: Authentication failed: HTTPConnectionPool(host='kc.example.bg', port=8080): Max retries exceeded with url: /auth/realms/kiwi/protocol/openid-connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab5b24bd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "social_django/views.py", line 31, in complete
    return do_complete(request.backend, _do_login, user=request.user,
  File "social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "social_core/utils.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "social_core/backends/oauth.py", line 382, in auth_complete
    response = self.request_access_token(
  File "social_core/backends/oauth.py", line 360, in request_access_token
    return self.get_json(*args, **kwargs)
  File "social_core/backends/base.py", line 242, in get_json
    return self.request(url, *args, **kwargs).json()
  File "social_core/backends/base.py", line 237, in request
    raise AuthFailed(self, str(err))
```

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

Full details are at https://github.com/kiwitcms/enterprise/pull/91 

1. A Django App with PSA installed. Here are my additional settings:

```
AUTHENTICATION_BACKENDS = [
   'social_core.backends.keycloak.KeycloakOAuth2',
   'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_KEYCLOAK_KEY = 'kiwitcms-web-app'
SOCIAL_AUTH_KEYCLOAK_SECRET = "...."
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = "...."
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = \
    "http://kc.example.bg:8080/auth/realms/kiwi/protocol/openid-connect/auth"
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = \
    "http://kc.example.bg:8080/auth/realms/kiwi/protocol/openid-connect/token"
```

2. Using a script (`testing/start_keycloak.sh`) I run the KC docker image and configure it according to the PSA docs from https://python-social-auth.readthedocs.io/en/latest/backends/keycloak.html
  - Keycloak server is at http://kc.example.bg:8080 - all domains are configured in /etc/hosts on the system and I can access them in the browser. 
  - new realm called `kiwi`
  - new client with user.info.response.signature.alg==RS256 and access type confidential and rootUrl=https://testing.example.bg:8443
  - 2 new users, called kc_bot and kc_atodorov, set password for kc_atodorov account (do this manually b/c script fails)
  - I can verify that I can login as kc_atodorov at http://kc.example.bg:8080/auth/realms/kiwi/account/

3. The script above exports the client secret and the RSA public key so I copy them into my settings.py and start the application afterwards
4. Go to https://testing.example.bg:8443/login/keycloak - works as expected, redirects to KS login window
5. Enter my correct username/password for KC which then redirects back to `https://testing.example.bg:8443/complete/keycloak/?redirect_state=...&state=....&session_state=...&code=...`
6. 500 error on the Django application side

### Any logs, error output, etc?

KC log shows:

1:35:17,971 WARN  [org.keycloak.services] (default task-2) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.

but I think this is unrelated.

### Any other comments?

From the PSA docs at the end of the page there is:

> Lastly you need to ensure the client_id is in your JWT’s aud key. On your client go to Mappers -> Create. Create an 
Audience Mapper and ensure the Included Client Audience is your client_id.

Inside the current version of Keycloak I can't figure out a way to configure this and I'm not sure if this is related or not.

Then the docs say:

> The default behaviour is to associate users via username field, but you
>    can change the key with e.g.
> 
> SOCIAL_AUTH_KEYCLOAK_ID_KEY = 'email'

I don't think this applies to us. From what I can tell the PSA code thinks that the authentication was wrong so it crashes before actually running any of the pipelines and creating/associating users, etc.

**Comment by nijel** [comment]
The error says "Name or service not known", maybe `kc.example.bg` does not resolve in your case?

**Comment by atodorov** [comment]
> The error says "Name or service not known", maybe `kc.example.bg` does not resolve in your case?

Hmm, good pointer, I didn't see that.  All of the hostnames, `kc.example.bg` and `testing.example.bg` are defined in `/etc/hosts` on the system starting the docker containers, but I bind these addresses to localhost. I'll try binding them to the actual addresses of each container and maybe also apply the same changes inside each container as well.

**Comment by atodorov** [comment]
@nijel I solved my problem. Thanks very much. The root cause was that the Django app (inside a container) didn't have network access to the kc.example.bg server due to how networking is configured inside the CI environment.
