### ISSUE TITLE
ORCID: backend crashes when no family name set in ORCID account

### ISSUE THREAD

**Issue by byte-for-byte** [python-social-auth/social-core#602]
### Expected behaviour

Successful login through ORCID backend.

### Actual behaviour

Authentication crashes with:
AttributeError: 'NoneType' object has no attribute 'get'

### What are the steps to reproduce this issue?

1) Create an ORCID account WITHOUT specifying a "Last Name".
2) Try social auth

### Any logs, error output, etc?

if "Last Name" is not provided in the ORCID account, 
name in .../backends/orcid.py", about line 77 will be 
name = {'created-date': {.... 'family-name': None, ....}

and in line 77, last_name = name.get('family-name', {}).get('value', '')

a get is used on a None type.

File ".../lib/python3.9/site-packages/social_core/backends/orcid.py", line 77, in get_user_details
  last_name = name.get('family-name', {}).get('value', '')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by nikoder** [comment]
This should be resolved on `master`, as of commit `95316b0914386af59d8649917c373a594f1766de`.
