### ISSUE TITLE
Twitch OAuth2 backend uses deprecated API

### ISSUE THREAD

**Issue by ghost** [python-social-auth/social-core#607]
### Expected behaviour

The Twitch backend should just work, however, when configured it will error out, as it makes an invalid call to an API that was deprecated and is set to be removed by the end of the year. Any authentication attempts fail with a call to the user information endpoint.

### Actual behaviour

The user should be able to authenticate and the call to the user info endpoint should succeed.

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Use the TwitchOAuth2 backend.
2. Sign in or connect an account to it.
3. Observe the error.

### Any logs, error output, etc?

It will throw an exception.

### Any other comments?

I've a working OpenIdConnect backend in my source tree, I am in the process of writing tests and documentation for it and will be making a pull request for it later today.

**Comment by bloodwithmilk25** [comment]
I made it work for my project, now I will created a pull request for it.
https://github.com/python-social-auth/social-core/pull/619
