### ISSUE TITLE
GooglePlusAuth Causes Errors When Used with an `id_token`

### ISSUE THREAD

**Issue by chrisguitarguy** [python-social-auth/social-core#61]
As far as I can tell, it's because the `id_token` is passed to [`do_auth`](https://github.com/python-social-auth/social-core/blob/40d700650c14711bda5637e2279612e630ef52cc/social_core/backends/google.py#L137-L144), which causes it to be passed to [`user_data`](https://github.com/python-social-auth/social-core/blob/40d700650c14711bda5637e2279612e630ef52cc/social_core/backends/google.py#L53-L61) in turn (via [`do_auth`](https://github.com/python-social-auth/social-core/blob/ef0a4d4aeedc04ec7d068fbbb317a72e6e182a4b/social_core/backends/oauth.py#L403)).

But an `id_token` apparently can't be used as an `access_token` and causes a...

> Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.

...error. Which I'm guessing is because the request is unauthenticated.

The tokeninfo endpoint for google+ should contain everything the backend needs, though. If there's a way to check for client side flow in `user_data` (like passing in a `token_type` argument or something?), it's possible that the user_data method can skip making an additional request.

Was able to work around this by subclassing `GooglePlusAuth` and returning `None` from `user_data` since I'm only using the client-side flow.

```python
from social_core.backends.google import GooglePlusAuth

class CustomGooglePlusAuth(GooglePlusAuth):
    def user_data(self, *args, **kwargs):
        return None
```

**Comment by gogson** [comment]
Thanks for the hack. A real fix would be nice indeed.

**Comment by gogson** [comment]
In my case I need the server-side flow (in order to use the social-auth pipelines.)

Here's my version, using the Google ```tokeninfo``` endpoint.
Now i'm getting the email address (enough for me at this moment)

```py
class CustomGooglePlusAuth(GooglePlusAuth):
    def user_data(self, access_token, *args, **kwargs):
      params = dict(id_token=access_token)
      resp = requests.get(url='https://www.googleapis.com/oauth2/v3/tokeninfo', params=params)
      return json.loads(resp.text)
```
