### ISSUE TITLE
Unable to process VK access token

### ISSUE THREAD

**Issue by c0derbug** [python-social-auth/social-core#611]
### Expected behaviour

The users.get method on the VK API backend should work!!!!

### Actual behaviour

I get the VK Backend access token, but I cannot process it into user data, because I get the error:

```
{"error":"access_denied","error_description":"Invalid request: versions below 5.81 are deprecated. Version param should be passed as \"v\". \"version\" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates"}
```

### What are the steps to reproduce this issue?

1. Go through all 6 steps indicated in the VK API article:
https://vk.com/dev/authcode_flow_user
2. You need to Send a request to VK API to receive user data
Request example:
https://api.vk.com/method/users.get?PARAMS&access_token=TOKEN&v=V
3. You will get the error above

### Any other comments?

Please update the version to the latest version of VK API (5.131)
The current versions of VK Api are presented at the link:
https://vk.com/dev/api_requests

Modify the file social_core/backends/vk.py line 182
`data['v'] = backend.setting('API_VERSION', '5.53')`
to this:
`data['v'] = backend.setting('API_VERSION', '5.131')`

**Comment by RustamF1** [comment]
@c0derbug 

add actual version to setting.py

`SOCIAL_AUTH_VK_OAUTH2_API_VERSION = '5.131'`

https://vk.com/dev/constant_version_updates

actual version:
https://vk.com/dev/versions
