### ISSUE TITLE
IMMUTABLE_USER_FIELDS overwrite non-social account fields

### ISSUE THREAD

**Issue by akhayyat** [python-social-auth/social-core#612]
### Expected behaviour

A pre-existing, non-social account retains its `IMMUTABLE_USER_FIELDS` when it's first associated with a social account.

### Actual behaviour

The `IMMUTABLE_USER_FIELDS` of a pre-existing, non-social account are overwritten on first association with a social account.

### What are the steps to reproduce this issue?

1. Set `IMMUTABLE_USER_FIELDS = ["email", "first_name", "last_name"]`.
2. Create a user that has nothing to do with social accounts.
3. Associate the user with a social account that uses different first name and last name from those set in the user created above.
4. Observe that this user's first name and last name are overwritten with the values retrieved from the social account.

### Any other comments?

The [documentation](https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#miscellaneous-settings) states that:

> This setting is similar to `SOCIAL_AUTH_PROTECTED_USER_FIELDS` in that they both do not allow changes of the data - however this one allows it to be set if no prior value exists.

The current behavior implies that the prior value must have been set by a social account, but the phrasing does not imply that. An account with prior values set locally, that has not been previously associated with a social account, should still be protected by this setting.

**Comment by nijel** [comment]
Maybe @keithhackbarth as author of https://github.com/python-social-auth/social-core/pull/582 can take a look at this?

**Comment by keithhackbarth** [comment]
Looking at [the code](https://github.com/python-social-auth/social-core/blob/eeee9763862d768627e134a42e4664456b6eabec/social_core/pipeline/user.py#L115), it seems like the value is only overwritten if the current value exists.

@akhayyat - Do you mind putting together a breaking test? Might help be better diagnose the issue. You can use this as a guide: https://github.com/python-social-auth/social-core/blob/master/social_core/tests/test_pipeline.py#L252

**Comment by akhayyat** [comment]
Sorry for the noise. After some head-scratching, I discovered that the version I'm using (current release on PyPI - 4.1.0) does not implement the `IMMUTABLE_USER_FIELDS` setting yet!

It's really confusing to have the online docs not match the current release. The docs say one thing, and the code does another.
