### ISSUE TITLE
Accept sponsorship/monetary contributions via Open Collective

### ISSUE THREAD

**Issue by leggetter** [python-social-auth/social-core#618]
I work for [PostHog](https://posthog.com), an open-source product analytics platform, that uses Python Social Auth - Core. We've recently set up an initiative to sponsor open-source projects that we use and benefit from. Where possible, we're trying to centrally manage this via [Open Collective](https://opencollective.com).

I've just set up a [pledge to Python Social Auth - Core](https://opencollective.com/python-social-authsocial-core) for PostHog in case you are willing to use Open Collective.

You can read more about what we're doing an why in this PR https://github.com/PostHog/posthog.com/pull/2077

Otherwise, if you'd like to get in touch directly, you can reach me via phil@posthog.com.

**Comment by nijel** [comment]
JFYI: This has been opened in https://github.com/python-social-auth/social-core/issues/445#issuecomment-596148881, but without much further discussions.

Speaking of myself, I can't spend more time on PSA even if it would be funded, my time is fully booked on @WeblateOrg, but I will continue to review pull requests in areas where I think I can understand them. On the other side, we might consider funding PSA as well if that will give it better maintenance (not sure if paying @omab is something he wants). Anyway, I've just added a small pledge as well on behalf of @WeblateOrg.

**Comment by tiago-peres** [comment]
Thanks for this... Just added a small pledge too.

**Comment by nijel** [comment]
https://opencollective.com/python-social-auth is now active. Let's see if we can get some proper funding there. It seems like the pledges didn't last that long, so please contribute now :smiley:.
