### ISSUE TITLE
Open redirect vulnerability in sanitize_redirect

### ISSUE THREAD

**Issue by AlabamaYarrow** [python-social-auth/social-core#62]
Util function sanitize_url [from here](https://github.com/python-social-auth/social-core/blob/master/social_core/utils.py#L86) is vulnerable to open redirect attack if redirect_to is something like **'////evil.com'**. In this case `urlparse(redirect_to)[1]` equals `''`, `netloc` is set to `hosts[0]` and value of redirect_to is returned.

```python  
def sanitize_redirect(hosts, redirect_to):
    if redirect_to:
        try:
            # if redirect_to is '////evil.com', urlparse(...)[1] is ''  
            netloc = urlparse(redirect_to)[1] or hosts[0]  # so we set netloc = hosts[0]
        except (TypeError, AttributeError):
            pass
        else:
            if netloc in hosts:  # yes, netloc in hosts
                return redirect_to  # returning '////evil.com' 
```

**Comment by nijel** [comment]
Probably something more complex like Django is using is needed instead, see https://github.com/django/django/blob/master/django/utils/http.py#L347

**Comment by nijel** [comment]
This is still valid, the current location of relevant Django code is here: https://github.com/django/django/blob/ffde4d5da88da6ed40ffc090503896d329bc67f8/django/utils/http.py#L302-L328
