### ISSUE TITLE
AzureADOAuth2 uses upn claim for email address

### ISSUE THREAD

**Issue by yrro** [python-social-auth/social-core#627]
The `upn` claim is not an email address. It might or might not be present, and if it is present, it might not be the user's email address (e.g., some of my users have a `upn` claim of `bob_consultant.com#EXT#@mydomain.com`).

https://github.com/python-social-auth/social-core/blob/17476e32ec16d3d0a4c261947a1dd814f3432bd5/social_core/backends/azuread.py#L73

There is an `email` claim that should be used instead.

For reference, the standard claims present in an ID Token are documented at https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens and the optional claims that may be present if the app asks for them are documented at https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims.

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-core/pull/629 should address this.
