### ISSUE TITLE
When will the new version come out?

### ISSUE THREAD

**Issue by denisSurkov** [python-social-auth/social-core#635]
Hi

I'm curios when the new version come out. New fixes would be useful for my python projects.

**Comment by qualitycoder** [comment]
+1 for new release. 
Twitch backend was updated in master in March. It is now Dec, and we still can't use new API. Old API has been deprecated, meaning Twitch backend itself is fully broken!!

**Comment by nijel** [comment]
It's probably time to do the release. Before doing that, I'd like to address a few issues:

* The SAML tests are broken (probably after change in SAML libs), help with fixing that is welcome.
* The new release should be tested against Python 3.10 (see https://github.com/python-social-auth/social-core/pull/647), blocked by SAML failures
* There are a lot of open pull requests, help with reviews is welcome.

**Comment by timabbott** [comment]
Is there an issue link for the SAML testing issue?

**Comment by nijel** [comment]
@timabbott: SAMLTest.test_login fails, for example see https://github.com/python-social-auth/social-core/runs/4531099732?check_suite_focus=true#step:6:571.

This has been discussed at https://github.com/python-social-auth/social-core/pull/590#issuecomment-997947634 as well.

**Comment by oasys** [comment]
Would love a release to incorporate #588, which fixes Okta auth in our environment.

**Comment by nijel** [comment]
Everything what has been merged will be incorporated, the blocker is still the broken SAML test.

**Comment by nijel** [comment]
https://pypi.org/project/social-auth-core/4.2.0/ ... I hope I didn't mess up anything as that is the first release published by me :-).
