### ISSUE TITLE
The Steam backend should use steamid instead of personaname to identify users

### ISSUE THREAD

**Issue by stefangeyer** [python-social-auth/social-core#64]
[Steam backend](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/steam.py#L27):

The personaname (display name on the profile) ist not unique and can therefore lead to errors, when multiple users with the same name try to log on. The steamid would provide a number as the username but is unique throughout Steam.

**Comment by Matoking** [comment]
This code seems to work just fine despite what it looks like at first glance.

The actual unique identifier is extracted by the _user_id function [here](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/steam.py#L43). The username parameter is for generating the username and it uses personaname. If an user with the same username is already registered in the Django app, it'll append a random string at the end (eg. my username Matoking could be saved with the username Matokinga52fas218)

**Comment by stefangeyer** [comment]
You are right, that is something I missed. But would you agree that adding a random string to gereate a unique username, insead of using the unique identifier that is delivered by the auth process, might lead to unwanted behaviour? After all, the django user model is the one that is queried most of the time.

**Comment by Matoking** [comment]
It is social-core's default behavior and one that can be [configured for different needs](http://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#username-generation). Also worth noting that the username is only generated once: if I login with my Steam username as *Matoking*, Django will create an User with the username *Matoking*. If I then log off, change my Steam nickname to *Atomking*, my Django user will still have the username *Matoking*.

If you want to use the SteamID as the username, you could override the [pipeline](http://python-social-auth.readthedocs.io/en/latest/pipeline.html#authentication-pipeline) step responsible for generating the username: the step you need to replace is *social_core.pipeline.user.get_username*. The SteamID should be exposed through the *details* keyword argument.
