### ISSUE TITLE
facebook oauth2 api_version

### ISSUE THREAD

**Issue by Tolikqq** [python-social-auth/social-core#649]
Need version facebook oauth2 is not 14 but 12.0

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-core/blob/1ea27e8989657bb35dd37b6ee2e038e1358fbc96/social_core/backends/facebook.py#L17

**Comment by Tolikqq** [comment]
> https://github.com/python-social-auth/social-core/blob/1ea27e8989657bb35dd37b6ee2e038e1358fbc96/social_core/backends/facebook.py#L17

Where you find version 14.0? 14.0 version does not exist. latest 12.0

**Comment by nijel** [comment]
Good point, I will fix that.
