### ISSUE TITLE
SAMLAuth extra_data

### ISSUE THREAD

**Issue by dblado** [python-social-auth/social-core#66]
I tried using SOCIAL_AUTH_SAML_EXTRA_DATA to get the extra attributes into UserSocialAuth.extra_data but I don't believe this has been implemented yet. I suppose it could be done by subclassing SAMLAuth and overriding _check_entitlements() but I think that would be an abuse of what that method is for. Probably the right fix is to implement a SAMLAuth().extra_data(). I'll take a stab at it but wanted to submit this issue to track it. Please someone correct me if I'm wrong.

**Comment by omab** [comment]
I've merged your PR related to this, I'll close the issue, but reopen if still relevant.

Thanks!
