### ISSUE TITLE
Discontinuation of Google Sign-In JavaScript Platform Library for web

### ISSUE THREAD

**Issue by ctan-wave** [python-social-auth/social-core#674]
Hello, 

Recently Google has announced that they be introducing Google Identity Services, and at the same time they will be discontinuing the Google Sign-In JavaScript Platform Library on March 31, 2023. Will there need to be any changes here or on the consumer's end to handle this?
Thanks!

https://developers.googleblog.com/2021/07/launching-our-new-google-identity-services-apis.html
https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-core/search?q=apis.google.com%2Fjs%2Fplatform.js does not show anything, so seems that social-core is not affected.
