### ISSUE TITLE
OpenID Connect does not support client_secret_basic Client Authentication method

### ISSUE THREAD

**Issue by derkoe** [python-social-auth/social-core#687]
### Expected behaviour

OpenID Connect specifies `client_secret_basic` as the default Client Authentication method (see https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest).

The actual method can be defined by the provider with the field `token_endpoint_auth_methods_supported` in the `.well-known/openid-configuration`. When this is not set the `client_secret_basic` method should be used.

### Actual behaviour

Currently the `OpenIdConnectAuth` always uses the `client_secret_post` method.

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Create your own backend with a provider that only supports client_secret_basic
2. Login 
3. The token verification will receive a 401 by the provider and the auth will fail

### Any other comments?

The best way to fix this would be to check for the `token_endpoint_auth_methods_supported` in the openid-configuration of the provider and then decide to use  `client_secret_basic` or `client_secret_post`

**Comment by derkoe** [comment]
If you need a backend that supports `client_secret_basic` you will have to override the `auth_headers` method:

```
class MyOpenIdAuth(OpenIdConnectAuth):
    name = 'my-openid'
    OIDC_ENDPOINT = 'https://my-openid.example.com'
    def auth_headers(self):
        """Adds the key and secret as basic auth header"""
        auth = base64.urlsafe_b64encode('{}:{}'.format(*self.get_key_and_secret()).encode()).decode()
        headers = {
            'Authorization': 'Basic {}'.format(auth),
            'Content-Type': 'application/x-www-form-urlencoded',
            'Accept': 'application/json'}
        return headers
```

**Comment by nijel** [comment]
See https://github.com/python-social-auth/social-core/pull/669
