### ISSUE TITLE
Offer ability to force google account chooser.

### ISSUE THREAD

**Issue by godd9170** [python-social-auth/social-core#69]
It's possible to force google to display the account chooser screen when the user is redirected to the `auth` endpoint by including a `prompt` query parameter. [This SO post](http://stackoverflow.com/a/14393492/7322725) goes into a bit more detail. 

My app has users logging in and out with different Google accounts, and the default google auth endpoint seems to remember the last account they'd authed with, and sharply bypasses the account chooser. 

I'm able to get the desired behaviour by adding `params['prompt'] = 'select_account'` to `social_core.backends.oauth.BaseOAuth2.auth_params` :

```py
    def auth_params(self, state=None):
        client_id, client_secret = self.get_key_and_secret()
        params = {
            'client_id': client_id,
            'redirect_uri': self.get_redirect_uri(state)
        }
        if self.STATE_PARAMETER and state:
            params['state'] = state
        if self.RESPONSE_TYPE:
            params['response_type'] = self.RESPONSE_TYPE
        
        params['prompt'] = 'select_account' ## <----  Adding in forced account chooser
        return params
```

I'm not exactly sure the best way to make this configurable, being the many levels of abstraction in this lib. Think you could point me in the right direction and I'll submit a PR @omab ?

**Comment by awachat** [comment]
Try this
In **settings.py**
```
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account'
}
```

**Comment by godd9170** [comment]
@awachat totally works. Thanks!
