### ISSUE TITLE
Store partial pipeline on a reusable way

### ISSUE THREAD

**Issue by omab** [python-social-auth/social-core#7]
Currently the partial pipeline heavily depends on the current framework session capabilities, this makes it really hard to resume a pipeline from another browser, a quite common pattern when a user clicks a validation link from an email and it popups in another browser.

Ideally, the pipeline state should be stored in a way that will allow such resume scenario.

**Comment by a1Gupta** [comment]
@omab There is a patch for it [here](https://gist.github.com/SaneMethod/b30156a3705ce9e944cd). It might help.

**Comment by omab** [comment]
This got implemented by https://github.com/python-social-auth/social-core/commit/a16b48e26f59fd63598ac9495d066891e49ab9e1 and the different frameworks also implemented the corresponding models. Docs coming soon.

**Comment by omab** [comment]
Version `1.0.0` released with this change.

**Comment by a1Gupta** [comment]
@omab I tried [django-example](https://github.com/python-social-auth/social-examples/tree/master/example-django) with twitter backend with following pipelines -

```
SOCIAL_AUTH_PIPELINE = (
   # other pipelines
    'social_core.pipeline.user.get_username',
    'common.pipeline.require_email',
    'social_core.pipeline.mail.mail_validation',
    'social_core.pipeline.user.create_user',
   # more pipelines
)
```

I am still getting `AuthMissingParameter at /complete/twitter/` `Missing needed parameter state` error in other browsers. The email verification link only has verification_code as query param. Can you tell how it will load data from `Partial` model from database ?

**Comment by jd-0001** [comment]
@a1Gupta Can you please share repo on how you performed pausing pipeline and resuming. Minimal example will be really useful.
