### ISSUE TITLE
Black linter

### ISSUE THREAD

**Issue by pfouque** [python-social-auth/social-core#721]
What about moving to black to lint the project?

**Comment by nijel** [comment]
I would not mind (using that already for most of other projects), but such change should get a wider agreement.

**Comment by digismack** [comment]
I'm fully behind this.

**Comment by pfouque** [comment]
I did some PR to have an idea
https://github.com/python-social-auth/social-app-django/pull/394
https://github.com/python-social-auth/social-core/pull/722

**Comment by pfouque** [comment]
@digismack @nijel is it a go for the other components (to move the whole project to black at once)?

**Comment by nijel** [comment]
I've merged existing PRs as there were no objections to that. It makes sense to do the similar change for other repos which are receiving some activity, but I'd probably skip the ones which were not touched for years.

**Comment by pfouque** [comment]
Thanks @nijel
