### ISSUE TITLE
Is this library still supported?

### ISSUE THREAD

**Issue by Nil-Andreu** [python-social-auth/social-core#740]
Hello!
Wanted to know if this library was still under maintenance/development, and if it needed support of more contributors/maintainers.

**Comment by nijel** [comment]
Yes, see https://github.com/python-social-auth/social-core/issues/445 and https://github.com/python-social-auth/social-core/issues/539.

**Comment by Nil-Andreu** [comment]
Okay thanks! Just applied for the possibility of be co-maintaner.
