### ISSUE TITLE
Add support for OpenInfra Open ID

### ISSUE THREAD

**Issue by ostackbrian** [python-social-auth/social-core#753]
### Proposed Feature

The OpenId provider at OpenStack was replaced a while ago by OpenInfra and will eventually be decommissioned.  Additionally, there are now users under the OpenInfra umbrella who never had an OpenStackId.  Thus it would be good to add a new backend to support OpenInfraOpenId.

### Any other comments?

I'll be submitting a PR shortly.

**Comment by nijel** [comment]
Fixed via https://github.com/python-social-auth/social-core/pull/754
