### ISSUE TITLE
OpenStackDevOpenId backend references non-existent provider

### ISSUE THREAD

**Issue by ostackbrian** [python-social-auth/social-core#755]
### Expected behaviour

The OpenStackDevOpenId backend should resolve to an existing provider.

### Actual behaviour

There's no longer anything at https://openstackid-dev.openstack.org 

### Any other comments?

It's not simply that the URL is incorrect, there is no development instance to resolve to.  I'll put up a PR to remove the backend.

**Comment by nijel** [comment]
Fixed by https://github.com/python-social-auth/social-core/pull/756
