### ISSUE TITLE
Unicode error with Facebook "'ascii' codec can't encode characters..."

### ISSUE THREAD

**Issue by Remiz** [python-social-auth/social-core#77]
Hello,

I'm using this package on production and from time to time I see an error poping in my logs when Facebook returns a non-ascii language error message to social-auth.

Here is the full error stack:
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
  File "django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 262, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "social_django/middleware.py", line 40, in process_exception
    message = self.get_message(request, exception)
  File "social_django/middleware.py", line 59, in get_message
    return six.text_type(exception)
  File "social_core/exceptions.py", line 49, in __str__
    msg = super(AuthCanceled, self).__str__()
```

The error message that was returned by Facebook was the following: `차단된 URL: 리다이렉트 URI가 앱의 클라이언트 OAuth 설정에서 허용되어 있지 않기 때문에 리다이렉트할 수 없었습니다. 클라이언트와 웹 OAuth 로그인이 켜져 있고 모든 앱 도메인이 유효한 OAuth 리다이렉트 URI인지 확인하세요.`.

I believe the error happens when social-auth is trying to retrieve the `error_message` parameter returned.

**Comment by aisayko** [comment]
+1

**Comment by sposs** [comment]
Faced the same problem right now. The message I have is in French. Looks like the issue is in the core, in the way the error_message is parsed. I suspect it's due to the use of the default `__str__` instead of one  that handles the unicode encoding.
The following 
``` python
def process_error(self, data):
        super(FacebookOAuth2, self).process_error(data)
        if data.get('error_code'):
            raise AuthCanceled(self, data.get('error_message') or
                                     data.get('error_code'))
```
should be
``` python
def process_error(self, data):
        super(FacebookOAuth2, self).process_error(data)
        if data.get('error_code'):
            raise AuthCanceled(self, data.get('error_message', "").encode("utf-8") or
                                     data.get('error_code'))
```
I think.

**Comment by skozan** [comment]
Experienced same error. We are using social-auth-app-django==2.1.0
Is there any fix in some newer version?

Thanks, Stefanos
