### ISSUE TITLE
get login url in code, rather than templates?

### ISSUE THREAD

**Issue by Pomax** [python-social-auth/social-core#78]
Is there a way to get the login URL that social auth uses to initial a login, for use in Python code rather than in some specific framework's templating language?

Django's template uses `<a href="{% url "social:begin" "google-oauth2" %}">Google+</a>` but it would be super useful (for third party, proxied logins) to be able to call that `url("social:begin", "google-oauth2")` with some kind of namespacing so that the `url(...)` function name doesn't collide.

How/where can this function be imported/called from?

(And would it be possible to put this in the docs for future searcher-of-information?)

**Comment by omab** [comment]
Default URLs on the different framework integrations can be overridden if needed, the different views/routes code is very simple so that they can be ignored and users can implement their own one.

This app won't provide a generic / framework agnostic way to build such URLs, there's plenty tools in the frameworks for such thing.

**Comment by Pomax** [comment]
that's not what I was asking though. I am currently doing this, which seems hacky as hell:
```
    # Get the real login URL from the social-auth system
    login_path_template = Template('{% url "social:begin" "google-oauth2" %}')
    login_path = login_path_template.render(Context({}))
    login_url = login_path + '?next=' + original_url

    return redirect(login_url)
```
So if there's a cleaner way to get the url that python-social-auth generates, I'll happily take it.

**Comment by omab** [comment]
@Pomax, you mean something like Django [reverse()](https://docs.djangoproject.com/en/1.11/ref/urlresolvers/#reverse) or Flask [url_for()](http://flask.pocoo.org/docs/0.12/api/#flask.url_for)?

**Comment by Pomax** [comment]
Those require already knowing what the URL is before you can reverse it, whereas I want to do it the other way: I don't know what the URL is, but I know what generates it. Sort of.

I'm basically looking for how to call something similar to `login_url = social_auth.url("social:begin", "google-oauth2")`, so using the same code that is used by the templating system in order to stay pythonic, without having to do that *through* the templating system. 

To explain why this code exists: this is a server that is both a normal Django instance combining site content and DRF data APIs, and so also acts as a login broken for various third party clients. They can call `/api/v1/login?original_url=...` which should cause a redirect chain: 

- login redirects to google login
- google login redirects to the `completed` callback url
- the post-login handler (pipeline function) then redirects back to the client's original url

nowhere in this chain is a page ever rendered by Django, it's all pure redirect logic. As such, the code that services this end point needs something in place to get the login URL through plain python code. I'm "abusing" the template system to make sure that happens right now, but a direct call to the same function that the templates use would be infinitely cleaner.

**Comment by omab** [comment]
[reverse()](https://docs.djangoproject.com/en/1.11/ref/urlresolvers/#reverse) is the opposite, you give it a view name and it will give you the path to it:

```
> from django.urls import reverse
> reverse("social:begin", args=["google-oauth2"])
u'/login/google-oauth2/'
```

**Comment by Pomax** [comment]
thanks. I didn't use the right call with `reverse()` then!
