### ISSUE TITLE
Stale

### ISSUE THREAD

**Issue by abigail1010** [python-social-auth/social-core#796]
### Expected behaviour

Describe what should happen.

### Actual behaviour

Describe what happens instead and why is it an issue.

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. ...
2. ...
3. ...

### Any logs, error output, etc?

Add any code, log or error output that you see fit for this issue, wrap any code
and / or console output with the proper code blocks.

### Any other comments?

Expand the issue with any details you find appropriate to solve or reproduce it.

**Comment by davidhalter** [comment]
No content was provided. Feel free to open a new ticket.
