### ISSUE TITLE
Twitter 0Auth2 not loading backend

### ISSUE THREAD

**Issue by JJZolper** [python-social-auth/social-core#842]
Error:

ModuleNotFoundError at /social-auth/login/twitter-oauth2/
No module named 'social_core.backends.twitter_oauth2'

settings.py:

# Social Auth
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.twitter_oauth2.TwitterOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

Following the code:

https://github.com/python-social-auth/social-core/blob/master/social_core/backends/twitter_oauth2.py

Not that much documentation, but: https://python-social-auth.readthedocs.io/en/latest/backends/twitter_oauth2.html

FYI

https://python-social-auth.readthedocs.io/en/latest/backends/twitter-oauth2.html

Link in the comments of the code linked above needs to be _ instead of -.

Any tips? I don't understand why this is happening when I'm directly pointing it to the class?

The login link in django:

`<a href="{% url 'social:begin' 'twitter-oauth2' %}" class="btn btn-primary btn-twitter"> Continue with Twitter</a>`

Versions:

social-auth-app-django==5.4.0
social-auth-core==4.4.2

**Comment by JJZolper** [comment]
I just looked in the Py 3.11 directory and the twitter_oauth2.py file is not there under social_core.backends so that certainly explains that.

Is there a reason the PR below was merged but this backend has not yet been included?

https://github.com/python-social-auth/social-core/pull/791

**Comment by JJZolper** [comment]
I copied the file into the directory and so far it probably needs more testing in a django app. Unsure yet why it doesn't work.

**Comment by yktakaha4** [comment]
The TwitterOAuth2 backend has been merged into master with the PR below, but no release has been created yet.
https://github.com/python-social-auth/social-core/pull/791

As a current workaround, you can use the entire library as a tgz file and load it as follows.
For poetry:

```toml
[tool.poetry.dependencies]
python = "3.7.13"
django = "~3.2"
social-auth-app-django = "~5.0"
social-auth-core = {path = "contrib/social-auth-core-master.tar.gz"}
```

**Comment by yktakaha4** [comment]
`4.5.0` supports TwitterOAuth2 :tada:
https://github.com/python-social-auth/social-core/releases/tag/4.5.0
