### ISSUE TITLE
OpenID Connect "at_hash" claim requirement during ID token validation

### ISSUE THREAD

**Issue by aaronmarkey** [python-social-auth/social-core#849]
### Expected behaviour

Per the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken), the `at_hash` claim in ID Token _can_ be optional, depending on circumstance. Thus, I'd expect ID token validation to succeed when the `at_hash` ID cliam is not required and not provided.

This was the actual behavior up to social-core 4.4.2.

### Actual behaviour

Since social-core version 4.5, the `OpenIdConnectAuth` backend incorrectly raises an `AuthTokenError` when the Authorization Code flow is used without the use of the `at_hash` claim in an ID token. 

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Use the `OpenIdConnectAuth` backend with the `code` `RESPONSE_TYPE`.
2. Make a request to a ID provider which does not include an `at_hash` claim in the ID token, such as Auth0.com.
3. Error occurs upon ID token validation.

### Any logs, error output, etc?

The problematic code in question is [here](https://github.com/python-social-auth/social-core/blob/6c69c603a6d2e614754ad3cb3e8de55ab46d159d/social_core/backends/open_id_connect.py#L239). This check should succeed when `at_hash` is not in the claim set, as is the behavior in the original `python-jose` [functionality](https://github.com/mpdavis/python-jose/blob/4b0701b46a8d00988afcc5168c2b3a1fd60d15d8/jose/jwt.py#L444C11-L444C11).

### Any other comments?

**Comment by nijel** [comment]
See also https://github.com/python-social-auth/social-core/issues/848#issuecomment-1790671405
