### ISSUE TITLE
Keycloak ID key change

### ISSUE THREAD

**Issue by nijel** [python-social-auth/social-core#854]
### Expected behaviour

Upgrade from 4.4.2 to 4.5.0 changes behavior of Keycloak authentication, see https://github.com/WeblateOrg/docker/issues/2048.

### Actual behaviour

https://github.com/python-social-auth/social-core/pull/815 by @derlin is probably the root cause here:

* It removes ID_KEY from the backend, makes it effectively use value from a parent class:
 
  https://github.com/python-social-auth/social-core/blob/b9d9937251b3f61435db8fca6203b516acbeea2e/social_core/backends/oauth.py#L43

* While this attribute is still used in the partial pipeline:
 
  https://github.com/python-social-auth/social-core/blob/b9d9937251b3f61435db8fca6203b516acbeea2e/social_core/utils.py#L192-L200

### Any other comments?

Possible solutions:

* Revert https://github.com/python-social-auth/social-core/pull/815 
* Make ID_KEY configurable for all backends, in a way that this breakage cannot happen

There is at least one additional backend (Seznam) affected by this.

**Comment by RJPercival** [comment]
I've created a revert PR (#858) since a fix PR doesn't seem to be forthcoming.

**Comment by derlin** [comment]
I am sorry for the disagreement, I really wasn't thinking this would be hardcoded in utils. I still believe having a way to configure the `ID_KEY` for OAuth-based backend is an important feature.

I unfortunately don't have time to provide a fix in the upcoming week, would someone else have some time to investigate?

**Comment by nijel** [comment]
I've merged that given we don't have a better solution now. https://github.com/python-social-auth/social-core/issues/862 is the issue to track this feature.
