### ISSUE TITLE
Optional deb/C dependencies

### ISSUE THREAD

**Issue by dotsbb** [python-social-auth/social-core#9]
@omab In https://github.com/python-social-auth/social-core/commit/25ca1f51b1e2e22521fdee33ac542ce2bcfb4da0  you have added new dependence `pyjwkest`. With this new requirement every `python-social-auth` user [has to install](https://pycryptodome.readthedocs.io/en/latest/src/installation.html#linux-ubuntu) `Cryptodome` with `build-essential libgmp3-dev python3-dev` debian packages (more than 50mb). 

Is it possible to use `extras_require` in `setup.py` to download that kind of dependencies optionally?

**Comment by omab** [comment]
I've removed the hard dependency, from now on if OpenIdConnect is required, it must be installed using the `openidconnect` extra:

```
$ pip install "social-auth-core[openidconnect]"
```

**Comment by omab** [comment]
FYI, I've published `social-auth-core 0.2.0` whit this change included.
