### ISSUE TITLE
partial_token not documented in pipeline docs

### ISSUE THREAD

**Issue by GregoryAveryWeir** [python-social-auth/social-core#91]
The docs say that SOCIAL_AUTH_EMAIL_VALIDATION_FUNCTION should take three arguments, but it now seems to take a fourth: `partial_token`. It's not in the documentation for email validation. I see it mentioned in the pipeline section, but it's unclear what changes should be made to make legacy code function. Can this be added to the documentation in more detail?

**Comment by remcinerney** [comment]
Do you know if this was added to the documentation? I'm still struggling to understand what's going on...

**Comment by omab** [comment]
This bit was added to the documentation https://python-social-auth.readthedocs.io/en/latest/pipeline.html#email-validation
