### ISSUE TITLE
Reauth Gitlab doesn't work

### ISSUE THREAD

**Issue by Spanish93** [python-social-auth/social-core#924]
Since Defect Dojo use last version of social core (5.4.1), reauth with gitlab don't work.
See : https://github.com/DefectDojo/django-DefectDojo/issues/10171

May be related with : https://github.com/python-social-auth/social-app

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-app-django/commit/7d8b75171ac6a67b215ac4adc7895f4a79141b01 should fix this, it's just needs a release.

**Comment by Spanish93** [comment]
OK and when can we expect a new release ?
