### ISSUE TITLE
URL not found for Linkedin OAuth2 Backend

### ISSUE THREAD

**Issue by tomasgarzon** [python-social-auth/social-core#94]
Hi, it seems there is a bug with LinkedinOAuth2 backend, because the URL for authorization has
- https://www.linkedin.com/uas/oauth2/authorization

but Linkedin docs says:
- https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=123456789&redirect_uri=https%3A%2F%2Fwww.example.com%2Fauth%2Flinkedin&state=987654321&scope=r_basicprofile

Thanks.

**Comment by omab** [comment]
Even with the URLs listed in their "docs", those `oauth/v2` URLs don't work.
